import { defineConfig } from 'vitepress'

// 微博官方 SVG 图标
const weiboSvg = `<svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path d="M851.4 590.193c-22.196-66.233-90.385-90.422-105.912-91.863-15.523-1.442-29.593-9.94-19.295-27.505 10.302-17.566 29.304-68.684-7.248-104.681-36.564-36.14-116.512-22.462-173.094 0.866-56.434 23.327-53.39 7.055-51.65-8.925 1.89-16.848 32.355-111.02-60.791-122.395C311.395 220.86 154.85 370.754 99.572 457.15 16 587.607 29.208 675.873 29.208 675.873h0.58c10.009 121.819 190.787 218.869 412.328 218.869 190.5 0 350.961-71.853 398.402-169.478 0 0 0.143-0.433 0.575-1.156 4.938-10.506 8.71-21.168 11.035-32.254 6.668-26.205 11.755-64.215-0.728-101.66z m-436.7 251.27c-157.71 0-285.674-84.095-285.674-187.768 0-103.671 127.82-187.76 285.674-187.76 157.705 0 285.673 84.089 285.673 187.76 0 103.815-127.968 187.768-285.673 187.768z" fill="currentColor"/><path d="M803.096 425.327c2.896 1.298 5.945 1.869 8.994 1.869 8.993 0 17.7-5.328 21.323-14.112 5.95-13.964 8.993-28.793 8.993-44.205 0-62.488-51.208-113.321-114.181-113.321-15.379 0-30.32 3.022-44.396 8.926-11.755 4.896-17.263 18.432-12.335 30.24 4.933 11.662 18.572 17.134 30.465 12.238 8.419-3.46 17.268-5.33 26.41-5.33 37.431 0 67.752 30.241 67.752 67.247 0 9.068-1.735 17.857-5.369 26.202a22.832 22.832 0 0 0 12.335 30.236z" fill="currentColor"/><path d="M726.922 114.157c-25.969 0-51.65 3.744-76.315 10.942-18.423 5.472-28.868 24.622-23.5 42.91 5.509 18.29 24.804 28.657 43.237 23.329a201.888 201.888 0 0 1 56.578-8.064c109.253 0 198.189 88.271 198.189 196.696 0 19.436-2.905 38.729-8.419 57.16-5.508 18.289 4.79 37.588 23.212 43.053 3.342 1.014 6.817 1.442 10.159 1.442 14.943 0 28.725-9.648 33.37-24.48 7.547-24.906 11.462-50.826 11.462-77.175-0.143-146.588-120.278-265.813-267.973-265.813z" fill="currentColor"/><path d="M388.294 534.47c-84.151 0-152.34 59.178-152.34 132.334 0 73.141 68.189 132.328 152.34 132.328 84.148 0 152.337-59.182 152.337-132.328 0-73.15-68.19-132.334-152.337-132.334zM338.53 752.763c-29.454 0-53.39-23.755-53.39-52.987 0-29.228 23.941-52.989 53.39-52.989 29.453 0 53.39 23.76 53.39 52.989 0 29.227-23.937 52.987-53.39 52.987z m99.82-95.465c-6.382 11.086-19.296 15.696-28.726 10.219-9.43-5.323-11.75-18.717-5.37-29.803 6.386-11.09 19.297-15.7 28.725-10.224 9.43 5.472 11.755 18.864 5.37 29.808z" fill="currentColor"/></svg>`

// 简体中文侧边栏
const zhSidebar = {
  '/zh/guide/': [
    {
      text: '开始使用',
      collapsed: false,
      items: [
        { text: '介绍',         link: '/zh/guide/introduction' },
        { text: '快速上手',     link: '/zh/guide/getting-started' },
        { text: '安装',         link: '/zh/guide/installation' },
        { text: '更新日志',     link: '/zh/guide/changelog' },
      ],
    },
    {
      text: '设计基础',
      collapsed: false,
      items: [
        { text: 'Design Tokens', link: '/zh/guide/tokens' },
        { text: '颜色系统',     link: '/zh/guide/colors' },
        { text: '字体规范',     link: '/zh/guide/typography' },
        { text: '间距规范',     link: '/zh/guide/spacing' },
        { text: '主题系统',     link: '/zh/guide/theming' },
        { text: '国际化 i18n', link: '/zh/guide/i18n' },
      ],
    },
    {
      text: '架构参考',
      collapsed: false,
      items: [
        { text: '架构概览',         link: '/zh/guide/architecture' },
        { text: 'Composables API', link: '/zh/guide/composables' },
        { text: '指令工具',         link: '/zh/guide/directives' },
        { text: '工具函数',         link: '/zh/guide/utils' },
      ],
    },
  ],
  '/zh/components/': [
    {
      text: '组件概览',
      collapsed: false,
      items: [
        { text: '组件概览', link: '/zh/components/overview' },
      ],
    },
    {
      text: '基础组件 Basic (41)',
      collapsed: true,
      items: [
        { text: '1. Color 颜色', link: '/zh/components/color' },
        { text: '2. Text 文本', link: '/zh/components/text' },
        { text: '3. Heading 标题', link: '/zh/components/heading' },
        { text: '4. Paragraph 段落', link: '/zh/components/paragraph' },
        { text: '5. Label 标签文本', link: '/zh/components/label' },
        { text: '6. Caption 说明文字', link: '/zh/components/caption' },
        { text: '7. Code 代码块', link: '/zh/components/code' },
        { text: '8. Quote 引用', link: '/zh/components/quote' },
        { text: '9. Number 数字', link: '/zh/components/number' },
        { text: '10. Statistic 统计数值', link: '/zh/components/statistic' },
        { text: '11. Counter 动画计数器', link: '/zh/components/counter' },
        { text: '12. Countdown 倒计时', link: '/zh/components/countdown' },
        { text: '13. Currency 货币', link: '/zh/components/currency' },
        { text: '14. Percentage 百分比', link: '/zh/components/percentage' },
        { text: '15. Icon 图标', link: '/zh/components/icon' },
        { text: '16. IconButton 图标按钮', link: '/zh/components/icon-button' },
        { text: '17. Button 按钮', link: '/zh/components/button' },
        { text: '18. ButtonGroup 按钮组', link: '/zh/components/button-group' },
        { text: '19. Link 链接', link: '/zh/components/link' },
        { text: '20. Divider 分割线', link: '/zh/components/divider' },
        { text: '21. Spacer 间距', link: '/zh/components/spacer' },
        { text: '22. Badge 徽标', link: '/zh/components/badge' },
        { text: '23. Tag 标签', link: '/zh/components/tag' },
        { text: '24. Chip 标签片', link: '/zh/components/chip' },
        { text: '25. Avatar 头像', link: '/zh/components/avatar' },
        { text: '26. AvatarGroup 头像组', link: '/zh/components/avatar-group' },
        { text: '27. Image 图片', link: '/zh/components/image' },
        { text: '28. Picture 图文', link: '/zh/components/picture' },
        { text: '29. AspectRatio 宽高比', link: '/zh/components/aspect-ratio' },
        { text: '30. Skeleton 骨架屏', link: '/zh/components/skeleton' },
        { text: '31. Spinner 加载旋转', link: '/zh/components/spinner' },
        { text: '32. Progress 进度条', link: '/zh/components/progress' },
        { text: '33. CircularProgress 环形进度', link: '/zh/components/circular-progress' },
        { text: '34. Rating 评分', link: '/zh/components/rating' },
        { text: '35. Switch 开关', link: '/zh/components/switch' },
        { text: '36. Slider 滑块', link: '/zh/components/slider' },
        { text: '37. RangeSlider 双滑块', link: '/zh/components/range-slider' },
        { text: '38. Clipboard 剪贴板', link: '/zh/components/clipboard' },
        { text: '39. CopyButton 复制按钮', link: '/zh/components/copy-button' },
        { text: '40. Highlight 高亮', link: '/zh/components/highlight' },
        { text: '41. VisuallyHidden 视觉隐藏', link: '/zh/components/visually-hidden' },
      ],
    },
    {
      text: '布局组件 Layout (32)',
      collapsed: true,
      items: [
        { text: '42. Container 容器', link: '/zh/components/container' },
        { text: '43. Flex 弹性布局', link: '/zh/components/flex' },
        { text: '44. Grid 网格布局', link: '/zh/components/grid' },
        { text: '45. Stack 堆叠布局', link: '/zh/components/stack' },
        { text: '46. HStack 水平堆叠', link: '/zh/components/h-stack' },
        { text: '47. VStack 垂直堆叠', link: '/zh/components/v-stack' },
        { text: '48. Center 居中容器', link: '/zh/components/center' },
        { text: '49. Space 间距容器', link: '/zh/components/space' },
        { text: '50. Wrap 自动换行', link: '/zh/components/wrap' },
        { text: '51. DividerLayout 分割布局', link: '/zh/components/divider-layout' },
        { text: '52. AspectRatioLayout 比例布局', link: '/zh/components/aspect-ratio-layout' },
        { text: '53. Page 页面容器', link: '/zh/components/page' },
        { text: '54. PageHeader 页头', link: '/zh/components/page-header' },
        { text: '55. PageFooter 页脚', link: '/zh/components/page-footer' },
        { text: '56. Section 区块', link: '/zh/components/section' },
        { text: '57. Sidebar 侧边栏', link: '/zh/components/sidebar' },
        { text: '58. SidebarLayout 侧边栏布局', link: '/zh/components/sidebar-layout' },
        { text: '59. HeaderLayout 顶栏布局', link: '/zh/components/header-layout' },
        { text: '60. FooterLayout 底栏布局', link: '/zh/components/footer-layout' },
        { text: '61. SplitLayout 分栏布局', link: '/zh/components/split-layout' },
        { text: '62. DashboardLayout 仪表盘布局', link: '/zh/components/dashboard-layout' },
        { text: '63. CardLayout 卡片布局', link: '/zh/components/card-layout' },
        { text: '64. ListLayout 列表布局', link: '/zh/components/list-layout' },
        { text: '65. MediaLayout 媒体布局', link: '/zh/components/media-layout' },
        { text: '66. ScrollView 滚动视图', link: '/zh/components/scroll-view' },
        { text: '67. Sticky 粘性定位', link: '/zh/components/sticky' },
        { text: '68. Portal 传送门', link: '/zh/components/portal' },
        { text: '69. Overlay 遮罩层', link: '/zh/components/overlay' },
        { text: '70. SafeArea 安全区域', link: '/zh/components/safe-area' },
        { text: '71. Viewport 视口容器', link: '/zh/components/viewport' },
        { text: '72. FixedLayout 固定布局', link: '/zh/components/fixed-layout' },
        { text: '73. FloatingLayout 浮动布局', link: '/zh/components/floating-layout' },
      ],
    },
    {
      text: '表单组件 Form (53)',
      collapsed: true,
      items: [
        { text: '74. Form 表单容器', link: '/zh/components/form' },
        { text: '75. FormItem 表单项', link: '/zh/components/form-item' },
        { text: '76. FormLabel 表单标签', link: '/zh/components/form-label' },
        { text: '77. FormDescription 表单描述', link: '/zh/components/form-description' },
        { text: '78. FormError 表单错误', link: '/zh/components/form-error' },
        { text: '79. FormGroup 表单分组', link: '/zh/components/form-group' },
        { text: '80. FormField 表单字段', link: '/zh/components/form-field' },
        { text: '81. Input 输入框', link: '/zh/components/input' },
        { text: '82. Textarea 文本域', link: '/zh/components/textarea' },
        { text: '83. PasswordInput 密码输入', link: '/zh/components/password-input' },
        { text: '84. NumberInput 数字输入', link: '/zh/components/number-input' },
        { text: '85. OtpInput 验证码输入', link: '/zh/components/otp-input' },
        { text: '86. SearchInput 搜索输入', link: '/zh/components/search-input' },
        { text: '87. UrlInput 网址输入', link: '/zh/components/url-input' },
        { text: '88. EmailInput 邮箱输入', link: '/zh/components/email-input' },
        { text: '89. PhoneInput 电话输入', link: '/zh/components/phone-input' },
        { text: '90. Select 下拉选择', link: '/zh/components/select' },
        { text: '91. MultiSelect 多选下拉', link: '/zh/components/multi-select' },
        { text: '92. TreeSelect 树形选择', link: '/zh/components/tree-select' },
        { text: '93. Cascader 级联选择', link: '/zh/components/cascader' },
        { text: '94. Checkbox 复选框', link: '/zh/components/checkbox' },
        { text: '95. CheckboxGroup 复选框组', link: '/zh/components/checkbox-group' },
        { text: '96. Radio 单选框', link: '/zh/components/radio' },
        { text: '97. RadioGroup 单选框组', link: '/zh/components/radio-group' },
        { text: '98. SwitchField 开关字段', link: '/zh/components/switch-field' },
        { text: '99. SliderField 滑块字段', link: '/zh/components/slider-field' },
        { text: '100. RangeSliderField 范围滑块字段', link: '/zh/components/range-slider-field' },
        { text: '101. RatingField 评分字段', link: '/zh/components/rating-field' },
        { text: '102. DatePicker 日期选择', link: '/zh/components/date-picker' },
        { text: '103. TimePicker 时间选择', link: '/zh/components/time-picker' },
        { text: '104. DateTimePicker 日期时间', link: '/zh/components/date-time-picker' },
        { text: '105. RangePicker 范围选择', link: '/zh/components/range-picker' },
        { text: '106. WeekPicker 周选择', link: '/zh/components/week-picker' },
        { text: '107. MonthPicker 月选择', link: '/zh/components/month-picker' },
        { text: '108. YearPicker 年选择', link: '/zh/components/year-picker' },
        { text: '109. ColorPicker 颜色选择器', link: '/zh/components/color-picker' },
        { text: '110. FileUpload 文件上传', link: '/zh/components/file-upload' },
        { text: '111. ImageUpload 图片上传', link: '/zh/components/image-upload' },
        { text: '112. Dropzone 拖拽上传区', link: '/zh/components/dropzone' },
        { text: '113. UploadList 上传列表', link: '/zh/components/upload-list' },
        { text: '114. SignaturePad 手写签名', link: '/zh/components/signature-pad' },
        { text: '115. RichTextEditor 富文本编辑', link: '/zh/components/rich-text-editor' },
        { text: '116. MarkdownEditor Markdown编辑', link: '/zh/components/markdown-editor' },
        { text: '117. JsonEditor JSON编辑器', link: '/zh/components/json-editor' },
        { text: '118. CodeEditor 代码编辑器', link: '/zh/components/code-editor' },
        { text: '119. TagInput 标签输入', link: '/zh/components/tag-input' },
        { text: '120. Autocomplete 自动完成', link: '/zh/components/autocomplete' },
        { text: '121. Mention 提及', link: '/zh/components/mention' },
        { text: '122. Transfer 穿梭框', link: '/zh/components/transfer' },
        { text: '123. DualList 双列表', link: '/zh/components/dual-list' },
        { text: '124. Stepper 步进器', link: '/zh/components/stepper' },
        { text: '125. WizardForm 向导表单', link: '/zh/components/wizard-form' },
        { text: '126. FormArray 动态表单', link: '/zh/components/form-array' },
      ],
    },
    {
      text: '数据组件 Data (18)',
      collapsed: true,
      items: [
        { text: '127. Table 表格', link: '/zh/components/table' },
        { text: '128. DataTable 数据表格', link: '/zh/components/data-table' },
        { text: '129. VirtualTable 虚拟表格', link: '/zh/components/virtual-table' },
        { text: '130. TreeTable 树形表格', link: '/zh/components/tree-table' },
        { text: '131. GridTable 网格表格', link: '/zh/components/grid-table' },
        { text: '132. List 列表', link: '/zh/components/list' },
        { text: '133. VirtualList 虚拟列表', link: '/zh/components/virtual-list' },
        { text: '134. Tree 树形控件', link: '/zh/components/tree' },
        { text: '135. DataGrid 数据网格', link: '/zh/components/data-grid' },
        { text: '136. StatisticCard 统计卡片', link: '/zh/components/statistic-card' },
        { text: '137. Metric 指标卡', link: '/zh/components/metric' },
        { text: '138. Timeline 时间线', link: '/zh/components/timeline' },
        { text: '139. Calendar 日历', link: '/zh/components/calendar' },
        { text: '140. Schedule 日程', link: '/zh/components/schedule' },
        { text: '141. ActivityFeed 动态流', link: '/zh/components/activity-feed' },
        { text: '142. Kanban 看板', link: '/zh/components/kanban' },
        { text: '143. DataCard 数据卡片', link: '/zh/components/data-card' },
        { text: '144. Waterfall 瀑布流', link: '/zh/components/waterfall' },
      ],
    },
    {
      text: '图表组件 Chart (14)',
      collapsed: true,
      items: [
        { text: '145. Chart 图表容器', link: '/zh/components/chart' },
        { text: '146. LineChart 折线图', link: '/zh/components/line-chart' },
        { text: '147. BarChart 柱状图', link: '/zh/components/bar-chart' },
        { text: '148. PieChart 饼图', link: '/zh/components/pie-chart' },
        { text: '149. AreaChart 面积图', link: '/zh/components/area-chart' },
        { text: '150. RadarChart 雷达图', link: '/zh/components/radar-chart' },
        { text: '151. ScatterChart 散点图', link: '/zh/components/scatter-chart' },
        { text: '152. Heatmap 热力图', link: '/zh/components/heatmap' },
        { text: '153. Gauge 仪表盘', link: '/zh/components/gauge' },
        { text: '154. Sparkline 迷你图', link: '/zh/components/sparkline' },
        { text: '155. Map 地图', link: '/zh/components/map' },
        { text: '156. GeoMap 地理地图', link: '/zh/components/geo-map' },
        { text: '157. FunnelChart 漏斗图', link: '/zh/components/funnel-chart' },
        { text: '158. TreemapChart 矩形树图', link: '/zh/components/treemap-chart' },
      ],
    },
    {
      text: '展示组件 Display (18)',
      collapsed: true,
      items: [
        { text: '159. DataViewer 数据查看器', link: '/zh/components/data-viewer' },
        { text: '160. JsonViewer JSON查看器', link: '/zh/components/json-viewer' },
        { text: '161. YamlViewer YAML查看器', link: '/zh/components/yaml-viewer' },
        { text: '162. KeyValue 键值对', link: '/zh/components/key-value' },
        { text: '163. LogViewer 日志查看器', link: '/zh/components/log-viewer' },
        { text: '164. CodeViewer 代码查看器', link: '/zh/components/code-viewer' },
        { text: '165. MarkdownViewer Markdown渲染', link: '/zh/components/markdown-viewer' },
        { text: '166. DiffViewer 差异对比', link: '/zh/components/diff-viewer' },
        { text: '167. FileTree 文件树', link: '/zh/components/file-tree' },
        { text: '168. FileList 文件列表', link: '/zh/components/file-list' },
        { text: '169. FolderTree 文件夹树', link: '/zh/components/folder-tree' },
        { text: '170. FolderList 文件夹列表', link: '/zh/components/folder-list' },
        { text: '171. MediaGallery 媒体画廊', link: '/zh/components/media-gallery' },
        { text: '172. ProductList 商品列表', link: '/zh/components/product-list' },
        { text: '173. UserList 用户列表', link: '/zh/components/user-list' },
        { text: '174. NotificationList 通知列表', link: '/zh/components/notification-list' },
        { text: '175. Watermark 水印', link: '/zh/components/watermark' },
        { text: '176. ProfileCard 个人名片', link: '/zh/components/profile-card' },
      ],
    },
    {
      text: '反馈组件 Feedback (30)',
      collapsed: true,
      items: [
        { text: '177. Alert 警告提示', link: '/zh/components/alert' },
        { text: '178. Banner 横幅', link: '/zh/components/banner' },
        { text: '179. Callout 标注', link: '/zh/components/callout' },
        { text: '180. Toast 轻提示', link: '/zh/components/toast' },
        { text: '181. Message 消息提示', link: '/zh/components/message' },
        { text: '182. Snackbar 操作提示', link: '/zh/components/snackbar' },
        { text: '183. Notification 通知', link: '/zh/components/notification' },
        { text: '184. NotificationCenter 通知中心', link: '/zh/components/notification-center' },
        { text: '185. Dialog 对话框', link: '/zh/components/dialog' },
        { text: '186. Modal 模态框', link: '/zh/components/modal' },
        { text: '187. ConfirmDialog 确认对话框', link: '/zh/components/confirm-dialog' },
        { text: '188. PromptDialog 输入对话框', link: '/zh/components/prompt-dialog' },
        { text: '189. FullscreenModal 全屏模态', link: '/zh/components/fullscreen-modal' },
        { text: '190. Drawer 抽屉', link: '/zh/components/drawer' },
        { text: '191. BottomSheet 底部面板', link: '/zh/components/bottom-sheet' },
        { text: '192. Popover 气泡卡片', link: '/zh/components/popover' },
        { text: '193. Tooltip 文字提示', link: '/zh/components/tooltip' },
        { text: '194. HoverCard 悬停卡片', link: '/zh/components/hover-card' },
        { text: '195. ContextMenu 右键菜单', link: '/zh/components/context-menu' },
        { text: '196. Loading 加载', link: '/zh/components/loading' },
        { text: '197. LoadingOverlay 加载遮罩', link: '/zh/components/loading-overlay' },
        { text: '198. ProgressBar 进度条', link: '/zh/components/progress-bar' },
        { text: '199. SkeletonLoader 骨架加载', link: '/zh/components/skeleton-loader' },
        { text: '200. EmptyState 空状态', link: '/zh/components/empty-state' },
        { text: '201. Result 结果页', link: '/zh/components/result' },
        { text: '202. ErrorPage 错误页', link: '/zh/components/error-page' },
        { text: '203. Offline 离线提示', link: '/zh/components/offline' },
        { text: '204. Retry 重试', link: '/zh/components/retry' },
        { text: '205. Tour 引导', link: '/zh/components/tour' },
        { text: '206. Guide 指南', link: '/zh/components/guide' },
      ],
    },
    {
      text: '导航组件 Navigation (23)',
      collapsed: true,
      items: [
        { text: '207. Menu 菜单', link: '/zh/components/menu' },
        { text: '208. MenuBar 菜单栏', link: '/zh/components/menu-bar' },
        { text: '209. DropdownMenu 下拉菜单', link: '/zh/components/dropdown-menu' },
        { text: '210. MegaMenu 超级菜单', link: '/zh/components/mega-menu' },
        { text: '211. Tabs 标签页', link: '/zh/components/tabs' },
        { text: '212. TabBar 标签栏', link: '/zh/components/tab-bar' },
        { text: '213. Breadcrumb 面包屑', link: '/zh/components/breadcrumb' },
        { text: '214. Pagination 分页', link: '/zh/components/pagination' },
        { text: '215. Pager 翻页器', link: '/zh/components/pager' },
        { text: '216. NavBar 导航栏', link: '/zh/components/nav-bar' },
        { text: '217. TopNav 顶部导航', link: '/zh/components/top-nav' },
        { text: '218. SideNav 侧边导航', link: '/zh/components/side-nav' },
        { text: '219. BottomNav 底部导航', link: '/zh/components/bottom-nav' },
        { text: '220. MobileNav 移动导航', link: '/zh/components/mobile-nav' },
        { text: '221. CommandPalette 命令面板', link: '/zh/components/command-palette' },
        { text: '222. SearchBar 搜索栏', link: '/zh/components/search-bar' },
        { text: '223. SearchDialog 搜索对话框', link: '/zh/components/search-dialog' },
        { text: '224. FilterBar 筛选栏', link: '/zh/components/filter-bar' },
        { text: '225. SortBar 排序栏', link: '/zh/components/sort-bar' },
        { text: '226. CategoryNav 分类导航', link: '/zh/components/category-nav' },
        { text: '227. TagNav 标签导航', link: '/zh/components/tag-nav' },
        { text: '228. AnchorNav 锚点导航', link: '/zh/components/anchor-nav' },
        { text: '229. FloatingMenu 浮动菜单', link: '/zh/components/floating-menu' },
      ],
    },
    {
      text: '媒体组件 Media (27)',
      collapsed: true,
      items: [
        { text: '230. ImageViewer 图片查看', link: '/zh/components/image-viewer' },
        { text: '231. ImagePreview 图片预览', link: '/zh/components/image-preview' },
        { text: '232. ImageZoom 图片缩放', link: '/zh/components/image-zoom' },
        { text: '233. ImageCropper 图片裁剪', link: '/zh/components/image-cropper' },
        { text: '234. ImageEditor 图片编辑', link: '/zh/components/image-editor' },
        { text: '235. Gallery 图库', link: '/zh/components/gallery' },
        { text: '236. Carousel 走马灯', link: '/zh/components/carousel' },
        { text: '237. SliderGallery 滑动画廊', link: '/zh/components/slider-gallery' },
        { text: '238. Lightbox 灯箱', link: '/zh/components/lightbox' },
        { text: '239. VideoPlayer 视频播放器', link: '/zh/components/video-player' },
        { text: '240. AudioPlayer 音频播放器', link: '/zh/components/audio-player' },
        { text: '241. MediaPlayer 媒体播放器', link: '/zh/components/media-player' },
        { text: '242. MediaCard 媒体卡片', link: '/zh/components/media-card' },
        { text: '243. MediaGrid 媒体网格', link: '/zh/components/media-grid' },
        { text: '244. Camera 相机', link: '/zh/components/camera' },
        { text: '245. ScreenRecorder 录屏', link: '/zh/components/screen-recorder' },
        { text: '246. AudioRecorder 录音', link: '/zh/components/audio-recorder' },
        { text: '247. QRScanner 二维码扫描', link: '/zh/components/qr-scanner' },
        { text: '248. BarcodeScanner 条码扫描', link: '/zh/components/barcode-scanner' },
        { text: '249. AvatarEditor 头像编辑', link: '/zh/components/avatar-editor' },
        { text: '250. GifPlayer GIF播放', link: '/zh/components/gif-player' },
        { text: '251. LottiePlayer Lottie播放', link: '/zh/components/lottie-player' },
        { text: '252. AnimationPlayer 动画播放', link: '/zh/components/animation-player' },
        { text: '253. PosterGenerator 海报生成', link: '/zh/components/poster-generator' },
        { text: '254. Thumbnail 缩略图', link: '/zh/components/thumbnail' },
        { text: '255. DocumentViewer 文档预览', link: '/zh/components/document-viewer' },
        { text: '256. Panorama 全景', link: '/zh/components/panorama' },
      ],
    },
    {
      text: '高级组件 Advanced (24)',
      collapsed: true,
      items: [
        { text: '257. GlobalSearch 全局搜索', link: '/zh/components/global-search' },
        { text: '258. Spotlight 聚光灯', link: '/zh/components/spotlight' },
        { text: '259. KanbanBoard 看板面板', link: '/zh/components/kanban-board' },
        { text: '260. WorkflowDesigner 工作流设计器', link: '/zh/components/workflow-designer' },
        { text: '261. FlowChart 流程图', link: '/zh/components/flow-chart' },
        { text: '262. MindMap 思维导图', link: '/zh/components/mind-map' },
        { text: '263. OrgChart 组织架构图', link: '/zh/components/org-chart' },
        { text: '264. TreeEditor 树编辑器', link: '/zh/components/tree-editor' },
        { text: '265. DragList 拖拽列表', link: '/zh/components/drag-list' },
        { text: '266. DragGrid 拖拽网格', link: '/zh/components/drag-grid' },
        { text: '267. DragTree 拖拽树', link: '/zh/components/drag-tree' },
        { text: '268. SortableList 可排序列表', link: '/zh/components/sortable-list' },
        { text: '269. SortableTable 可排序表格', link: '/zh/components/sortable-table' },
        { text: '270. VirtualScroller 虚拟滚动', link: '/zh/components/virtual-scroller' },
        { text: '271. InfiniteScroll 无限滚动', link: '/zh/components/infinite-scroll' },
        { text: '272. SmartTable 智能表格', link: '/zh/components/smart-table' },
        { text: '273. QueryBuilder 查询构建器', link: '/zh/components/query-builder' },
        { text: '274. FilterBuilder 筛选构建器', link: '/zh/components/filter-builder' },
        { text: '275. LayoutBuilder 布局构建器', link: '/zh/components/layout-builder' },
        { text: '276. DashboardBuilder 仪表盘构建器', link: '/zh/components/dashboard-builder' },
        { text: '277. PageBuilder 页面构建器', link: '/zh/components/page-builder' },
        { text: '278. ThemeEditor 主题编辑器', link: '/zh/components/theme-editor' },
        { text: '279. ComponentPlayground 组件演练场', link: '/zh/components/component-playground' },
        { text: '280. LiveEditor 实时编辑器', link: '/zh/components/live-editor' },
      ],
    },
    {
      text: '工具组件 Utility (20)',
      collapsed: true,
      items: [
        { text: '281. FocusTrap 焦点陷阱', link: '/zh/components/focus-trap' },
        { text: '282. ClickOutside 外部点击', link: '/zh/components/click-outside' },
        { text: '283. ResizeObserver 尺寸监听', link: '/zh/components/resize-observer' },
        { text: '284. IntersectionObserver 交叉监听', link: '/zh/components/intersection-observer' },
        { text: '285. ScrollLock 滚动锁定', link: '/zh/components/scroll-lock' },
        { text: '286. ScrollSpy 滚动监听', link: '/zh/components/scroll-spy' },
        { text: '287. Keybinding 快捷键绑定', link: '/zh/components/keybinding' },
        { text: '288. Hotkey 热键', link: '/zh/components/hotkey' },
        { text: '289. ClipboardManager 剪贴板管理', link: '/zh/components/clipboard-manager' },
        { text: '290. Fullscreen 全屏', link: '/zh/components/fullscreen' },
        { text: '291. IdleTimer 空闲计时', link: '/zh/components/idle-timer' },
        { text: '292. VisibilitySensor 可见性传感', link: '/zh/components/visibility-sensor' },
        { text: '293. DeviceDetector 设备检测', link: '/zh/components/device-detector' },
        { text: '294. ThemeProvider 主题提供者', link: '/zh/components/theme-provider' },
        { text: '295. LocaleProvider 语言提供者', link: '/zh/components/locale-provider' },
        { text: '296. ConfigProvider 配置提供者', link: '/zh/components/config-provider' },
        { text: '297. ErrorBoundary 错误边界', link: '/zh/components/error-boundary' },
        { text: '298. RenderIf 条件渲染', link: '/zh/components/render-if' },
        { text: '299. Breakpoint 断点检测', link: '/zh/components/breakpoint' },
        { text: '300. MediaQuery 媒体查询', link: '/zh/components/media-query' },
      ],
    },
  ],
}

// 繁体中文侧边栏
const zhTWSidebar = {
  '/zh-HK/guide/': [
    {
      text: '開始使用',
      collapsed: false,
      items: [
        { text: '介紹',     link: '/zh-HK/guide/introduction' },
        { text: '快速上手', link: '/zh-HK/guide/getting-started' },
        { text: '安裝',     link: '/zh-HK/guide/installation' },
        { text: '更新日誌', link: '/zh-HK/guide/changelog' },
      ],
    },
    {
      text: '設計基礎',
      collapsed: false,
      items: [
        { text: 'Design Tokens', link: '/zh-HK/guide/tokens' },
        { text: '顏色系統',     link: '/zh-HK/guide/colors' },
        { text: '字體規範',     link: '/zh-HK/guide/typography' },
        { text: '間距規範',     link: '/zh-HK/guide/spacing' },
        { text: '主題系統',     link: '/zh-HK/guide/theming' },
      ],
    },
  ],
  '/zh-HK/components/': [
    {
      text: '元件概覽',
      collapsed: false,
      items: [
        { text: '元件概覽', link: '/zh-HK/components/overview' },
      ],
    },
    {
      text: '基礎元件 Basic (41)',
      collapsed: true,
      items: [
        { text: '1. Color 顏色', link: '/zh-HK/components/color' },
        { text: '2. Text 文字', link: '/zh-HK/components/text' },
        { text: '3. Heading 標題', link: '/zh-HK/components/heading' },
        { text: '4. Paragraph 段落', link: '/zh-HK/components/paragraph' },
        { text: '5. Label 標籤文字', link: '/zh-HK/components/label' },
        { text: '6. Caption 說明文字', link: '/zh-HK/components/caption' },
        { text: '7. Code 程式碼區塊', link: '/zh-HK/components/code' },
        { text: '8. Quote 引用', link: '/zh-HK/components/quote' },
        { text: '9. Number 數字', link: '/zh-HK/components/number' },
        { text: '10. Statistic 統計數值', link: '/zh-HK/components/statistic' },
        { text: '11. Counter 動畫計數器', link: '/zh-HK/components/counter' },
        { text: '12. Countdown 倒數計時', link: '/zh-HK/components/countdown' },
        { text: '13. Currency 貨幣', link: '/zh-HK/components/currency' },
        { text: '14. Percentage 百分比', link: '/zh-HK/components/percentage' },
        { text: '15. Icon 圖示', link: '/zh-HK/components/icon' },
        { text: '16. IconButton 圖示按鈕', link: '/zh-HK/components/icon-button' },
        { text: '17. Button 按鈕', link: '/zh-HK/components/button' },
        { text: '18. ButtonGroup 按鈕組', link: '/zh-HK/components/button-group' },
        { text: '19. Link 連結', link: '/zh-HK/components/link' },
        { text: '20. Divider 分割線', link: '/zh-HK/components/divider' },
        { text: '21. Spacer 間距', link: '/zh-HK/components/spacer' },
        { text: '22. Badge 徽標', link: '/zh-HK/components/badge' },
        { text: '23. Tag 標籤', link: '/zh-HK/components/tag' },
        { text: '24. Chip 標籤片', link: '/zh-HK/components/chip' },
        { text: '25. Avatar 頭像', link: '/zh-HK/components/avatar' },
        { text: '26. AvatarGroup 頭像組', link: '/zh-HK/components/avatar-group' },
        { text: '27. Image 圖片', link: '/zh-HK/components/image' },
        { text: '28. Picture 圖文', link: '/zh-HK/components/picture' },
        { text: '29. AspectRatio 寬高比', link: '/zh-HK/components/aspect-ratio' },
        { text: '30. Skeleton 骨架屏', link: '/zh-HK/components/skeleton' },
        { text: '31. Spinner 載入旋轉', link: '/zh-HK/components/spinner' },
        { text: '32. Progress 進度條', link: '/zh-HK/components/progress' },
        { text: '33. CircularProgress 環形進度', link: '/zh-HK/components/circular-progress' },
        { text: '34. Rating 評分', link: '/zh-HK/components/rating' },
        { text: '35. Switch 開關', link: '/zh-HK/components/switch' },
        { text: '36. Slider 滑塊', link: '/zh-HK/components/slider' },
        { text: '37. RangeSlider 雙滑塊', link: '/zh-HK/components/range-slider' },
        { text: '38. Clipboard 剪貼簿', link: '/zh-HK/components/clipboard' },
        { text: '39. CopyButton 複製按鈕', link: '/zh-HK/components/copy-button' },
        { text: '40. Highlight 高亮', link: '/zh-HK/components/highlight' },
        { text: '41. VisuallyHidden 視覺隱藏', link: '/zh-HK/components/visually-hidden' },
      ],
    },
    {
      text: '佈局元件 Layout (32)',
      collapsed: true,
      items: [
        { text: '42. Container 容器', link: '/zh-HK/components/container' },
        { text: '43. Flex 彈性佈局', link: '/zh-HK/components/flex' },
        { text: '44. Grid 網格佈局', link: '/zh-HK/components/grid' },
        { text: '45. Stack 堆疊佈局', link: '/zh-HK/components/stack' },
        { text: '46. HStack 水平堆疊', link: '/zh-HK/components/h-stack' },
        { text: '47. VStack 垂直堆疊', link: '/zh-HK/components/v-stack' },
        { text: '48. Center 置中容器', link: '/zh-HK/components/center' },
        { text: '49. Space 間距容器', link: '/zh-HK/components/space' },
        { text: '50. Wrap 自動換行', link: '/zh-HK/components/wrap' },
        { text: '51. DividerLayout 分割佈局', link: '/zh-HK/components/divider-layout' },
        { text: '52. AspectRatioLayout 比例佈局', link: '/zh-HK/components/aspect-ratio-layout' },
        { text: '53. Page 頁面容器', link: '/zh-HK/components/page' },
        { text: '54. PageHeader 頁首', link: '/zh-HK/components/page-header' },
        { text: '55. PageFooter 頁尾', link: '/zh-HK/components/page-footer' },
        { text: '56. Section 區塊', link: '/zh-HK/components/section' },
        { text: '57. Sidebar 側邊欄', link: '/zh-HK/components/sidebar' },
        { text: '58. SidebarLayout 側邊欄佈局', link: '/zh-HK/components/sidebar-layout' },
        { text: '59. HeaderLayout 頂欄佈局', link: '/zh-HK/components/header-layout' },
        { text: '60. FooterLayout 底欄佈局', link: '/zh-HK/components/footer-layout' },
        { text: '61. SplitLayout 分欄佈局', link: '/zh-HK/components/split-layout' },
        { text: '62. DashboardLayout 儀表盤佈局', link: '/zh-HK/components/dashboard-layout' },
        { text: '63. CardLayout 卡片佈局', link: '/zh-HK/components/card-layout' },
        { text: '64. ListLayout 列表佈局', link: '/zh-HK/components/list-layout' },
        { text: '65. MediaLayout 媒體佈局', link: '/zh-HK/components/media-layout' },
        { text: '66. ScrollView 捲動視圖', link: '/zh-HK/components/scroll-view' },
        { text: '67. Sticky 黏性定位', link: '/zh-HK/components/sticky' },
        { text: '68. Portal 傳送門', link: '/zh-HK/components/portal' },
        { text: '69. Overlay 遮罩層', link: '/zh-HK/components/overlay' },
        { text: '70. SafeArea 安全區域', link: '/zh-HK/components/safe-area' },
        { text: '71. Viewport 視口容器', link: '/zh-HK/components/viewport' },
        { text: '72. FixedLayout 固定佈局', link: '/zh-HK/components/fixed-layout' },
        { text: '73. FloatingLayout 浮動佈局', link: '/zh-HK/components/floating-layout' },
      ],
    },
    {
      text: '表單元件 Form (53)',
      collapsed: true,
      items: [
        { text: '74. Form 表單容器', link: '/zh-HK/components/form' },
        { text: '75. FormItem 表單項', link: '/zh-HK/components/form-item' },
        { text: '76. FormLabel 表單標籤', link: '/zh-HK/components/form-label' },
        { text: '77. FormDescription 表單描述', link: '/zh-HK/components/form-description' },
        { text: '78. FormError 表單錯誤', link: '/zh-HK/components/form-error' },
        { text: '79. FormGroup 表單分組', link: '/zh-HK/components/form-group' },
        { text: '80. FormField 表單欄位', link: '/zh-HK/components/form-field' },
        { text: '81. Input 輸入框', link: '/zh-HK/components/input' },
        { text: '82. Textarea 文字域', link: '/zh-HK/components/textarea' },
        { text: '83. PasswordInput 密碼輸入', link: '/zh-HK/components/password-input' },
        { text: '84. NumberInput 數字輸入', link: '/zh-HK/components/number-input' },
        { text: '85. OtpInput 驗證碼輸入', link: '/zh-HK/components/otp-input' },
        { text: '86. SearchInput 搜尋輸入', link: '/zh-HK/components/search-input' },
        { text: '87. UrlInput 網址輸入', link: '/zh-HK/components/url-input' },
        { text: '88. EmailInput 郵箱輸入', link: '/zh-HK/components/email-input' },
        { text: '89. PhoneInput 電話輸入', link: '/zh-HK/components/phone-input' },
        { text: '90. Select 下拉選擇', link: '/zh-HK/components/select' },
        { text: '91. MultiSelect 多選下拉', link: '/zh-HK/components/multi-select' },
        { text: '92. TreeSelect 樹形選擇', link: '/zh-HK/components/tree-select' },
        { text: '93. Cascader 級聯選擇', link: '/zh-HK/components/cascader' },
        { text: '94. Checkbox 複選框', link: '/zh-HK/components/checkbox' },
        { text: '95. CheckboxGroup 複選框組', link: '/zh-HK/components/checkbox-group' },
        { text: '96. Radio 單選框', link: '/zh-HK/components/radio' },
        { text: '97. RadioGroup 單選框組', link: '/zh-HK/components/radio-group' },
        { text: '98. SwitchField 開關欄位', link: '/zh-HK/components/switch-field' },
        { text: '99. SliderField 滑塊欄位', link: '/zh-HK/components/slider-field' },
        { text: '100. RangeSliderField 範圍滑塊欄位', link: '/zh-HK/components/range-slider-field' },
        { text: '101. RatingField 評分欄位', link: '/zh-HK/components/rating-field' },
        { text: '102. DatePicker 日期選擇', link: '/zh-HK/components/date-picker' },
        { text: '103. TimePicker 時間選擇', link: '/zh-HK/components/time-picker' },
        { text: '104. DateTimePicker 日期時間', link: '/zh-HK/components/date-time-picker' },
        { text: '105. RangePicker 範圍選擇', link: '/zh-HK/components/range-picker' },
        { text: '106. WeekPicker 週選擇', link: '/zh-HK/components/week-picker' },
        { text: '107. MonthPicker 月選擇', link: '/zh-HK/components/month-picker' },
        { text: '108. YearPicker 年選擇', link: '/zh-HK/components/year-picker' },
        { text: '109. ColorPicker 顏色選擇器', link: '/zh-HK/components/color-picker' },
        { text: '110. FileUpload 檔案上傳', link: '/zh-HK/components/file-upload' },
        { text: '111. ImageUpload 圖片上傳', link: '/zh-HK/components/image-upload' },
        { text: '112. Dropzone 拖拽上傳區', link: '/zh-HK/components/dropzone' },
        { text: '113. UploadList 上傳列表', link: '/zh-HK/components/upload-list' },
        { text: '114. SignaturePad 手寫簽名', link: '/zh-HK/components/signature-pad' },
        { text: '115. RichTextEditor 富文字編輯', link: '/zh-HK/components/rich-text-editor' },
        { text: '116. MarkdownEditor Markdown編輯', link: '/zh-HK/components/markdown-editor' },
        { text: '117. JsonEditor JSON編輯器', link: '/zh-HK/components/json-editor' },
        { text: '118. CodeEditor 程式碼編輯器', link: '/zh-HK/components/code-editor' },
        { text: '119. TagInput 標籤輸入', link: '/zh-HK/components/tag-input' },
        { text: '120. Autocomplete 自動完成', link: '/zh-HK/components/autocomplete' },
        { text: '121. Mention 提及', link: '/zh-HK/components/mention' },
        { text: '122. Transfer 穿梭框', link: '/zh-HK/components/transfer' },
        { text: '123. DualList 雙列表', link: '/zh-HK/components/dual-list' },
        { text: '124. Stepper 步進器', link: '/zh-HK/components/stepper' },
        { text: '125. WizardForm 嚮導表單', link: '/zh-HK/components/wizard-form' },
        { text: '126. FormArray 動態表單', link: '/zh-HK/components/form-array' },
      ],
    },
    {
      text: '數據元件 Data (18)',
      collapsed: true,
      items: [
        { text: '127. Table 表格', link: '/zh-HK/components/table' },
        { text: '128. DataTable 數據表格', link: '/zh-HK/components/data-table' },
        { text: '129. VirtualTable 虛擬表格', link: '/zh-HK/components/virtual-table' },
        { text: '130. TreeTable 樹形表格', link: '/zh-HK/components/tree-table' },
        { text: '131. GridTable 網格表格', link: '/zh-HK/components/grid-table' },
        { text: '132. List 列表', link: '/zh-HK/components/list' },
        { text: '133. VirtualList 虛擬列表', link: '/zh-HK/components/virtual-list' },
        { text: '134. Tree 樹形控件', link: '/zh-HK/components/tree' },
        { text: '135. DataGrid 數據網格', link: '/zh-HK/components/data-grid' },
        { text: '136. StatisticCard 統計卡片', link: '/zh-HK/components/statistic-card' },
        { text: '137. Metric 指標卡', link: '/zh-HK/components/metric' },
        { text: '138. Timeline 時間線', link: '/zh-HK/components/timeline' },
        { text: '139. Calendar 日曆', link: '/zh-HK/components/calendar' },
        { text: '140. Schedule 日程', link: '/zh-HK/components/schedule' },
        { text: '141. ActivityFeed 動態流', link: '/zh-HK/components/activity-feed' },
        { text: '142. Kanban 看板', link: '/zh-HK/components/kanban' },
        { text: '143. DataCard 數據卡片', link: '/zh-HK/components/data-card' },
        { text: '144. Waterfall 瀑布流', link: '/zh-HK/components/waterfall' },
      ],
    },
    {
      text: '圖表元件 Chart (14)',
      collapsed: true,
      items: [
        { text: '145. Chart 圖表容器', link: '/zh-HK/components/chart' },
        { text: '146. LineChart 折線圖', link: '/zh-HK/components/line-chart' },
        { text: '147. BarChart 柱狀圖', link: '/zh-HK/components/bar-chart' },
        { text: '148. PieChart 餅圖', link: '/zh-HK/components/pie-chart' },
        { text: '149. AreaChart 面積圖', link: '/zh-HK/components/area-chart' },
        { text: '150. RadarChart 雷達圖', link: '/zh-HK/components/radar-chart' },
        { text: '151. ScatterChart 散點圖', link: '/zh-HK/components/scatter-chart' },
        { text: '152. Heatmap 熱力圖', link: '/zh-HK/components/heatmap' },
        { text: '153. Gauge 儀表盤', link: '/zh-HK/components/gauge' },
        { text: '154. Sparkline 迷你圖', link: '/zh-HK/components/sparkline' },
        { text: '155. Map 地圖', link: '/zh-HK/components/map' },
        { text: '156. GeoMap 地理地圖', link: '/zh-HK/components/geo-map' },
        { text: '157. FunnelChart 漏斗圖', link: '/zh-HK/components/funnel-chart' },
        { text: '158. TreemapChart 矩形樹圖', link: '/zh-HK/components/treemap-chart' },
      ],
    },
    {
      text: '展示元件 Display (18)',
      collapsed: true,
      items: [
        { text: '159. DataViewer 數據查看器', link: '/zh-HK/components/data-viewer' },
        { text: '160. JsonViewer JSON查看器', link: '/zh-HK/components/json-viewer' },
        { text: '161. YamlViewer YAML查看器', link: '/zh-HK/components/yaml-viewer' },
        { text: '162. KeyValue 鍵值對', link: '/zh-HK/components/key-value' },
        { text: '163. LogViewer 日誌查看器', link: '/zh-HK/components/log-viewer' },
        { text: '164. CodeViewer 程式碼查看器', link: '/zh-HK/components/code-viewer' },
        { text: '165. MarkdownViewer Markdown渲染', link: '/zh-HK/components/markdown-viewer' },
        { text: '166. DiffViewer 差異對比', link: '/zh-HK/components/diff-viewer' },
        { text: '167. FileTree 檔案樹', link: '/zh-HK/components/file-tree' },
        { text: '168. FileList 檔案列表', link: '/zh-HK/components/file-list' },
        { text: '169. FolderTree 資料夾樹', link: '/zh-HK/components/folder-tree' },
        { text: '170. FolderList 資料夾列表', link: '/zh-HK/components/folder-list' },
        { text: '171. MediaGallery 媒體畫廊', link: '/zh-HK/components/media-gallery' },
        { text: '172. ProductList 商品列表', link: '/zh-HK/components/product-list' },
        { text: '173. UserList 用戶列表', link: '/zh-HK/components/user-list' },
        { text: '174. NotificationList 通知列表', link: '/zh-HK/components/notification-list' },
        { text: '175. Watermark 浮水印', link: '/zh-HK/components/watermark' },
        { text: '176. ProfileCard 個人名片', link: '/zh-HK/components/profile-card' },
      ],
    },
    {
      text: '回饋元件 Feedback (30)',
      collapsed: true,
      items: [
        { text: '177. Alert 警告提示', link: '/zh-HK/components/alert' },
        { text: '178. Banner 橫幅', link: '/zh-HK/components/banner' },
        { text: '179. Callout 標註', link: '/zh-HK/components/callout' },
        { text: '180. Toast 輕提示', link: '/zh-HK/components/toast' },
        { text: '181. Message 訊息提示', link: '/zh-HK/components/message' },
        { text: '182. Snackbar 操作提示', link: '/zh-HK/components/snackbar' },
        { text: '183. Notification 通知', link: '/zh-HK/components/notification' },
        { text: '184. NotificationCenter 通知中心', link: '/zh-HK/components/notification-center' },
        { text: '185. Dialog 對話框', link: '/zh-HK/components/dialog' },
        { text: '186. Modal 模態框', link: '/zh-HK/components/modal' },
        { text: '187. ConfirmDialog 確認對話框', link: '/zh-HK/components/confirm-dialog' },
        { text: '188. PromptDialog 輸入對話框', link: '/zh-HK/components/prompt-dialog' },
        { text: '189. FullscreenModal 全螢幕模態', link: '/zh-HK/components/fullscreen-modal' },
        { text: '190. Drawer 抽屜', link: '/zh-HK/components/drawer' },
        { text: '191. BottomSheet 底部面板', link: '/zh-HK/components/bottom-sheet' },
        { text: '192. Popover 氣泡卡片', link: '/zh-HK/components/popover' },
        { text: '193. Tooltip 文字提示', link: '/zh-HK/components/tooltip' },
        { text: '194. HoverCard 懸停卡片', link: '/zh-HK/components/hover-card' },
        { text: '195. ContextMenu 右鍵選單', link: '/zh-HK/components/context-menu' },
        { text: '196. Loading 載入', link: '/zh-HK/components/loading' },
        { text: '197. LoadingOverlay 載入遮罩', link: '/zh-HK/components/loading-overlay' },
        { text: '198. ProgressBar 進度條', link: '/zh-HK/components/progress-bar' },
        { text: '199. SkeletonLoader 骨架載入', link: '/zh-HK/components/skeleton-loader' },
        { text: '200. EmptyState 空狀態', link: '/zh-HK/components/empty-state' },
        { text: '201. Result 結果頁', link: '/zh-HK/components/result' },
        { text: '202. ErrorPage 錯誤頁', link: '/zh-HK/components/error-page' },
        { text: '203. Offline 離線提示', link: '/zh-HK/components/offline' },
        { text: '204. Retry 重試', link: '/zh-HK/components/retry' },
        { text: '205. Tour 引導', link: '/zh-HK/components/tour' },
        { text: '206. Guide 指南', link: '/zh-HK/components/guide' },
      ],
    },
    {
      text: '導航元件 Navigation (23)',
      collapsed: true,
      items: [
        { text: '207. Menu 選單', link: '/zh-HK/components/menu' },
        { text: '208. MenuBar 選單列', link: '/zh-HK/components/menu-bar' },
        { text: '209. DropdownMenu 下拉選單', link: '/zh-HK/components/dropdown-menu' },
        { text: '210. MegaMenu 超級選單', link: '/zh-HK/components/mega-menu' },
        { text: '211. Tabs 標籤頁', link: '/zh-HK/components/tabs' },
        { text: '212. TabBar 標籤列', link: '/zh-HK/components/tab-bar' },
        { text: '213. Breadcrumb 麵包屑', link: '/zh-HK/components/breadcrumb' },
        { text: '214. Pagination 分頁', link: '/zh-HK/components/pagination' },
        { text: '215. Pager 翻頁器', link: '/zh-HK/components/pager' },
        { text: '216. NavBar 導航列', link: '/zh-HK/components/nav-bar' },
        { text: '217. TopNav 頂部導航', link: '/zh-HK/components/top-nav' },
        { text: '218. SideNav 側邊導航', link: '/zh-HK/components/side-nav' },
        { text: '219. BottomNav 底部導航', link: '/zh-HK/components/bottom-nav' },
        { text: '220. MobileNav 行動導航', link: '/zh-HK/components/mobile-nav' },
        { text: '221. CommandPalette 命令面板', link: '/zh-HK/components/command-palette' },
        { text: '222. SearchBar 搜尋列', link: '/zh-HK/components/search-bar' },
        { text: '223. SearchDialog 搜尋對話框', link: '/zh-HK/components/search-dialog' },
        { text: '224. FilterBar 篩選列', link: '/zh-HK/components/filter-bar' },
        { text: '225. SortBar 排序列', link: '/zh-HK/components/sort-bar' },
        { text: '226. CategoryNav 分類導航', link: '/zh-HK/components/category-nav' },
        { text: '227. TagNav 標籤導航', link: '/zh-HK/components/tag-nav' },
        { text: '228. AnchorNav 錨點導航', link: '/zh-HK/components/anchor-nav' },
        { text: '229. FloatingMenu 浮動選單', link: '/zh-HK/components/floating-menu' },
      ],
    },
    {
      text: '媒體元件 Media (27)',
      collapsed: true,
      items: [
        { text: '230. ImageViewer 圖片查看', link: '/zh-HK/components/image-viewer' },
        { text: '231. ImagePreview 圖片預覽', link: '/zh-HK/components/image-preview' },
        { text: '232. ImageZoom 圖片縮放', link: '/zh-HK/components/image-zoom' },
        { text: '233. ImageCropper 圖片裁剪', link: '/zh-HK/components/image-cropper' },
        { text: '234. ImageEditor 圖片編輯', link: '/zh-HK/components/image-editor' },
        { text: '235. Gallery 圖庫', link: '/zh-HK/components/gallery' },
        { text: '236. Carousel 走馬燈', link: '/zh-HK/components/carousel' },
        { text: '237. SliderGallery 滑動畫廊', link: '/zh-HK/components/slider-gallery' },
        { text: '238. Lightbox 燈箱', link: '/zh-HK/components/lightbox' },
        { text: '239. VideoPlayer 影片播放器', link: '/zh-HK/components/video-player' },
        { text: '240. AudioPlayer 音訊播放器', link: '/zh-HK/components/audio-player' },
        { text: '241. MediaPlayer 媒體播放器', link: '/zh-HK/components/media-player' },
        { text: '242. MediaCard 媒體卡片', link: '/zh-HK/components/media-card' },
        { text: '243. MediaGrid 媒體網格', link: '/zh-HK/components/media-grid' },
        { text: '244. Camera 相機', link: '/zh-HK/components/camera' },
        { text: '245. ScreenRecorder 錄屏', link: '/zh-HK/components/screen-recorder' },
        { text: '246. AudioRecorder 錄音', link: '/zh-HK/components/audio-recorder' },
        { text: '247. QRScanner 二維碼掃描', link: '/zh-HK/components/qr-scanner' },
        { text: '248. BarcodeScanner 條碼掃描', link: '/zh-HK/components/barcode-scanner' },
        { text: '249. AvatarEditor 頭像編輯', link: '/zh-HK/components/avatar-editor' },
        { text: '250. GifPlayer GIF播放', link: '/zh-HK/components/gif-player' },
        { text: '251. LottiePlayer Lottie播放', link: '/zh-HK/components/lottie-player' },
        { text: '252. AnimationPlayer 動畫播放', link: '/zh-HK/components/animation-player' },
        { text: '253. PosterGenerator 海報生成', link: '/zh-HK/components/poster-generator' },
        { text: '254. Thumbnail 縮圖', link: '/zh-HK/components/thumbnail' },
        { text: '255. DocumentViewer 文件預覽', link: '/zh-HK/components/document-viewer' },
        { text: '256. Panorama 全景', link: '/zh-HK/components/panorama' },
      ],
    },
    {
      text: '進階元件 Advanced (24)',
      collapsed: true,
      items: [
        { text: '257. GlobalSearch 全域搜尋', link: '/zh-HK/components/global-search' },
        { text: '258. Spotlight 聚光燈', link: '/zh-HK/components/spotlight' },
        { text: '259. KanbanBoard 看板面板', link: '/zh-HK/components/kanban-board' },
        { text: '260. WorkflowDesigner 工作流設計器', link: '/zh-HK/components/workflow-designer' },
        { text: '261. FlowChart 流程圖', link: '/zh-HK/components/flow-chart' },
        { text: '262. MindMap 心智圖', link: '/zh-HK/components/mind-map' },
        { text: '263. OrgChart 組織架構圖', link: '/zh-HK/components/org-chart' },
        { text: '264. TreeEditor 樹編輯器', link: '/zh-HK/components/tree-editor' },
        { text: '265. DragList 拖拽列表', link: '/zh-HK/components/drag-list' },
        { text: '266. DragGrid 拖拽網格', link: '/zh-HK/components/drag-grid' },
        { text: '267. DragTree 拖拽樹', link: '/zh-HK/components/drag-tree' },
        { text: '268. SortableList 可排序列表', link: '/zh-HK/components/sortable-list' },
        { text: '269. SortableTable 可排序表格', link: '/zh-HK/components/sortable-table' },
        { text: '270. VirtualScroller 虛擬捲動', link: '/zh-HK/components/virtual-scroller' },
        { text: '271. InfiniteScroll 無限捲動', link: '/zh-HK/components/infinite-scroll' },
        { text: '272. SmartTable 智慧表格', link: '/zh-HK/components/smart-table' },
        { text: '273. QueryBuilder 查詢建構器', link: '/zh-HK/components/query-builder' },
        { text: '274. FilterBuilder 篩選建構器', link: '/zh-HK/components/filter-builder' },
        { text: '275. LayoutBuilder 佈局建構器', link: '/zh-HK/components/layout-builder' },
        { text: '276. DashboardBuilder 儀表盤建構器', link: '/zh-HK/components/dashboard-builder' },
        { text: '277. PageBuilder 頁面建構器', link: '/zh-HK/components/page-builder' },
        { text: '278. ThemeEditor 主題編輯器', link: '/zh-HK/components/theme-editor' },
        { text: '279. ComponentPlayground 元件演練場', link: '/zh-HK/components/component-playground' },
        { text: '280. LiveEditor 即時編輯器', link: '/zh-HK/components/live-editor' },
      ],
    },
    {
      text: '工具元件 Utility (20)',
      collapsed: true,
      items: [
        { text: '281. FocusTrap 焦點陷阱', link: '/zh-HK/components/focus-trap' },
        { text: '282. ClickOutside 外部點擊', link: '/zh-HK/components/click-outside' },
        { text: '283. ResizeObserver 尺寸監聽', link: '/zh-HK/components/resize-observer' },
        { text: '284. IntersectionObserver 交叉監聽', link: '/zh-HK/components/intersection-observer' },
        { text: '285. ScrollLock 捲動鎖定', link: '/zh-HK/components/scroll-lock' },
        { text: '286. ScrollSpy 捲動監聽', link: '/zh-HK/components/scroll-spy' },
        { text: '287. Keybinding 快捷鍵綁定', link: '/zh-HK/components/keybinding' },
        { text: '288. Hotkey 熱鍵', link: '/zh-HK/components/hotkey' },
        { text: '289. ClipboardManager 剪貼簿管理', link: '/zh-HK/components/clipboard-manager' },
        { text: '290. Fullscreen 全螢幕', link: '/zh-HK/components/fullscreen' },
        { text: '291. IdleTimer 閒置計時', link: '/zh-HK/components/idle-timer' },
        { text: '292. VisibilitySensor 可見性偵測', link: '/zh-HK/components/visibility-sensor' },
        { text: '293. DeviceDetector 裝置偵測', link: '/zh-HK/components/device-detector' },
        { text: '294. ThemeProvider 主題提供者', link: '/zh-HK/components/theme-provider' },
        { text: '295. LocaleProvider 語言提供者', link: '/zh-HK/components/locale-provider' },
        { text: '296. ConfigProvider 配置提供者', link: '/zh-HK/components/config-provider' },
        { text: '297. ErrorBoundary 錯誤邊界', link: '/zh-HK/components/error-boundary' },
        { text: '298. RenderIf 條件渲染', link: '/zh-HK/components/render-if' },
        { text: '299. Breakpoint 斷點偵測', link: '/zh-HK/components/breakpoint' },
        { text: '300. MediaQuery 媒體查詢', link: '/zh-HK/components/media-query' },
      ],
    },
  ],
}

// 英文侧边栏
const enSidebar = {
  '/en/guide/': [
    {
      text: 'Getting Started',
      collapsed: false,
      items: [
        { text: 'Introduction',  link: '/en/guide/introduction' },
        { text: 'Quick Start',   link: '/en/guide/getting-started' },
        { text: 'Installation',  link: '/en/guide/installation' },
        { text: 'Changelog',     link: '/en/guide/changelog' },
      ],
    },
    {
      text: 'Design',
      collapsed: false,
      items: [
        { text: 'Design Tokens', link: '/en/guide/tokens' },
        { text: 'Colors',        link: '/en/guide/colors' },
        { text: 'Typography',    link: '/en/guide/typography' },
        { text: 'Spacing',       link: '/en/guide/spacing' },
        { text: 'Theming',       link: '/en/guide/theming' },
      ],
    },
    {
      text: 'Architecture',
      collapsed: false,
      items: [
        { text: 'Overview',       link: '/en/guide/architecture' },
        { text: 'Composables',    link: '/en/guide/composables' },
        { text: 'Directives',     link: '/en/guide/directives' },
        { text: 'Utils',          link: '/en/guide/utils' },
      ],
    },
  ],
  '/en/components/': [
    {
      text: 'Overview',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/en/components/overview' },
      ],
    },
    {
      text: 'Basic (41)',
      collapsed: true,
      items: [
        { text: '1. Color', link: '/en/components/color' },
        { text: '2. Text', link: '/en/components/text' },
        { text: '3. Heading', link: '/en/components/heading' },
        { text: '4. Paragraph', link: '/en/components/paragraph' },
        { text: '5. Label', link: '/en/components/label' },
        { text: '6. Caption', link: '/en/components/caption' },
        { text: '7. Code', link: '/en/components/code' },
        { text: '8. Quote', link: '/en/components/quote' },
        { text: '9. Number', link: '/en/components/number' },
        { text: '10. Statistic', link: '/en/components/statistic' },
        { text: '11. Counter', link: '/en/components/counter' },
        { text: '12. Countdown', link: '/en/components/countdown' },
        { text: '13. Currency', link: '/en/components/currency' },
        { text: '14. Percentage', link: '/en/components/percentage' },
        { text: '15. Icon', link: '/en/components/icon' },
        { text: '16. IconButton', link: '/en/components/icon-button' },
        { text: '17. Button', link: '/en/components/button' },
        { text: '18. ButtonGroup', link: '/en/components/button-group' },
        { text: '19. Link', link: '/en/components/link' },
        { text: '20. Divider', link: '/en/components/divider' },
        { text: '21. Spacer', link: '/en/components/spacer' },
        { text: '22. Badge', link: '/en/components/badge' },
        { text: '23. Tag', link: '/en/components/tag' },
        { text: '24. Chip', link: '/en/components/chip' },
        { text: '25. Avatar', link: '/en/components/avatar' },
        { text: '26. AvatarGroup', link: '/en/components/avatar-group' },
        { text: '27. Image', link: '/en/components/image' },
        { text: '28. Picture', link: '/en/components/picture' },
        { text: '29. AspectRatio', link: '/en/components/aspect-ratio' },
        { text: '30. Skeleton', link: '/en/components/skeleton' },
        { text: '31. Spinner', link: '/en/components/spinner' },
        { text: '32. Progress', link: '/en/components/progress' },
        { text: '33. CircularProgress', link: '/en/components/circular-progress' },
        { text: '34. Rating', link: '/en/components/rating' },
        { text: '35. Switch', link: '/en/components/switch' },
        { text: '36. Slider', link: '/en/components/slider' },
        { text: '37. RangeSlider', link: '/en/components/range-slider' },
        { text: '38. Clipboard', link: '/en/components/clipboard' },
        { text: '39. CopyButton', link: '/en/components/copy-button' },
        { text: '40. Highlight', link: '/en/components/highlight' },
        { text: '41. VisuallyHidden', link: '/en/components/visually-hidden' },
      ],
    },
    {
      text: 'Layout (32)',
      collapsed: true,
      items: [
        { text: '42. Container', link: '/en/components/container' },
        { text: '43. Flex', link: '/en/components/flex' },
        { text: '44. Grid', link: '/en/components/grid' },
        { text: '45. Stack', link: '/en/components/stack' },
        { text: '46. HStack', link: '/en/components/h-stack' },
        { text: '47. VStack', link: '/en/components/v-stack' },
        { text: '48. Center', link: '/en/components/center' },
        { text: '49. Space', link: '/en/components/space' },
        { text: '50. Wrap', link: '/en/components/wrap' },
        { text: '51. DividerLayout', link: '/en/components/divider-layout' },
        { text: '52. AspectRatioLayout', link: '/en/components/aspect-ratio-layout' },
        { text: '53. Page', link: '/en/components/page' },
        { text: '54. PageHeader', link: '/en/components/page-header' },
        { text: '55. PageFooter', link: '/en/components/page-footer' },
        { text: '56. Section', link: '/en/components/section' },
        { text: '57. Sidebar', link: '/en/components/sidebar' },
        { text: '58. SidebarLayout', link: '/en/components/sidebar-layout' },
        { text: '59. HeaderLayout', link: '/en/components/header-layout' },
        { text: '60. FooterLayout', link: '/en/components/footer-layout' },
        { text: '61. SplitLayout', link: '/en/components/split-layout' },
        { text: '62. DashboardLayout', link: '/en/components/dashboard-layout' },
        { text: '63. CardLayout', link: '/en/components/card-layout' },
        { text: '64. ListLayout', link: '/en/components/list-layout' },
        { text: '65. MediaLayout', link: '/en/components/media-layout' },
        { text: '66. ScrollView', link: '/en/components/scroll-view' },
        { text: '67. Sticky', link: '/en/components/sticky' },
        { text: '68. Portal', link: '/en/components/portal' },
        { text: '69. Overlay', link: '/en/components/overlay' },
        { text: '70. SafeArea', link: '/en/components/safe-area' },
        { text: '71. Viewport', link: '/en/components/viewport' },
        { text: '72. FixedLayout', link: '/en/components/fixed-layout' },
        { text: '73. FloatingLayout', link: '/en/components/floating-layout' },
      ],
    },
    {
      text: 'Form (53)',
      collapsed: true,
      items: [
        { text: '74. Form', link: '/en/components/form' },
        { text: '75. FormItem', link: '/en/components/form-item' },
        { text: '76. FormLabel', link: '/en/components/form-label' },
        { text: '77. FormDescription', link: '/en/components/form-description' },
        { text: '78. FormError', link: '/en/components/form-error' },
        { text: '79. FormGroup', link: '/en/components/form-group' },
        { text: '80. FormField', link: '/en/components/form-field' },
        { text: '81. Input', link: '/en/components/input' },
        { text: '82. Textarea', link: '/en/components/textarea' },
        { text: '83. PasswordInput', link: '/en/components/password-input' },
        { text: '84. NumberInput', link: '/en/components/number-input' },
        { text: '85. OtpInput', link: '/en/components/otp-input' },
        { text: '86. SearchInput', link: '/en/components/search-input' },
        { text: '87. UrlInput', link: '/en/components/url-input' },
        { text: '88. EmailInput', link: '/en/components/email-input' },
        { text: '89. PhoneInput', link: '/en/components/phone-input' },
        { text: '90. Select', link: '/en/components/select' },
        { text: '91. MultiSelect', link: '/en/components/multi-select' },
        { text: '92. TreeSelect', link: '/en/components/tree-select' },
        { text: '93. Cascader', link: '/en/components/cascader' },
        { text: '94. Checkbox', link: '/en/components/checkbox' },
        { text: '95. CheckboxGroup', link: '/en/components/checkbox-group' },
        { text: '96. Radio', link: '/en/components/radio' },
        { text: '97. RadioGroup', link: '/en/components/radio-group' },
        { text: '98. SwitchField', link: '/en/components/switch-field' },
        { text: '99. SliderField', link: '/en/components/slider-field' },
        { text: '100. RangeSliderField', link: '/en/components/range-slider-field' },
        { text: '101. RatingField', link: '/en/components/rating-field' },
        { text: '102. DatePicker', link: '/en/components/date-picker' },
        { text: '103. TimePicker', link: '/en/components/time-picker' },
        { text: '104. DateTimePicker', link: '/en/components/date-time-picker' },
        { text: '105. RangePicker', link: '/en/components/range-picker' },
        { text: '106. WeekPicker', link: '/en/components/week-picker' },
        { text: '107. MonthPicker', link: '/en/components/month-picker' },
        { text: '108. YearPicker', link: '/en/components/year-picker' },
        { text: '109. ColorPicker', link: '/en/components/color-picker' },
        { text: '110. FileUpload', link: '/en/components/file-upload' },
        { text: '111. ImageUpload', link: '/en/components/image-upload' },
        { text: '112. Dropzone', link: '/en/components/dropzone' },
        { text: '113. UploadList', link: '/en/components/upload-list' },
        { text: '114. SignaturePad', link: '/en/components/signature-pad' },
        { text: '115. RichTextEditor', link: '/en/components/rich-text-editor' },
        { text: '116. MarkdownEditor', link: '/en/components/markdown-editor' },
        { text: '117. JsonEditor', link: '/en/components/json-editor' },
        { text: '118. CodeEditor', link: '/en/components/code-editor' },
        { text: '119. TagInput', link: '/en/components/tag-input' },
        { text: '120. Autocomplete', link: '/en/components/autocomplete' },
        { text: '121. Mention', link: '/en/components/mention' },
        { text: '122. Transfer', link: '/en/components/transfer' },
        { text: '123. DualList', link: '/en/components/dual-list' },
        { text: '124. Stepper', link: '/en/components/stepper' },
        { text: '125. WizardForm', link: '/en/components/wizard-form' },
        { text: '126. FormArray', link: '/en/components/form-array' },
      ],
    },
    {
      text: 'Data (18)',
      collapsed: true,
      items: [
        { text: '127. Table', link: '/en/components/table' },
        { text: '128. DataTable', link: '/en/components/data-table' },
        { text: '129. VirtualTable', link: '/en/components/virtual-table' },
        { text: '130. TreeTable', link: '/en/components/tree-table' },
        { text: '131. GridTable', link: '/en/components/grid-table' },
        { text: '132. List', link: '/en/components/list' },
        { text: '133. VirtualList', link: '/en/components/virtual-list' },
        { text: '134. Tree', link: '/en/components/tree' },
        { text: '135. DataGrid', link: '/en/components/data-grid' },
        { text: '136. StatisticCard', link: '/en/components/statistic-card' },
        { text: '137. Metric', link: '/en/components/metric' },
        { text: '138. Timeline', link: '/en/components/timeline' },
        { text: '139. Calendar', link: '/en/components/calendar' },
        { text: '140. Schedule', link: '/en/components/schedule' },
        { text: '141. ActivityFeed', link: '/en/components/activity-feed' },
        { text: '142. Kanban', link: '/en/components/kanban' },
        { text: '143. DataCard', link: '/en/components/data-card' },
        { text: '144. Waterfall', link: '/en/components/waterfall' },
      ],
    },
    {
      text: 'Chart (14)',
      collapsed: true,
      items: [
        { text: '145. Chart', link: '/en/components/chart' },
        { text: '146. LineChart', link: '/en/components/line-chart' },
        { text: '147. BarChart', link: '/en/components/bar-chart' },
        { text: '148. PieChart', link: '/en/components/pie-chart' },
        { text: '149. AreaChart', link: '/en/components/area-chart' },
        { text: '150. RadarChart', link: '/en/components/radar-chart' },
        { text: '151. ScatterChart', link: '/en/components/scatter-chart' },
        { text: '152. Heatmap', link: '/en/components/heatmap' },
        { text: '153. Gauge', link: '/en/components/gauge' },
        { text: '154. Sparkline', link: '/en/components/sparkline' },
        { text: '155. Map', link: '/en/components/map' },
        { text: '156. GeoMap', link: '/en/components/geo-map' },
        { text: '157. FunnelChart', link: '/en/components/funnel-chart' },
        { text: '158. TreemapChart', link: '/en/components/treemap-chart' },
      ],
    },
    {
      text: 'Display (18)',
      collapsed: true,
      items: [
        { text: '159. DataViewer', link: '/en/components/data-viewer' },
        { text: '160. JsonViewer', link: '/en/components/json-viewer' },
        { text: '161. YamlViewer', link: '/en/components/yaml-viewer' },
        { text: '162. KeyValue', link: '/en/components/key-value' },
        { text: '163. LogViewer', link: '/en/components/log-viewer' },
        { text: '164. CodeViewer', link: '/en/components/code-viewer' },
        { text: '165. MarkdownViewer', link: '/en/components/markdown-viewer' },
        { text: '166. DiffViewer', link: '/en/components/diff-viewer' },
        { text: '167. FileTree', link: '/en/components/file-tree' },
        { text: '168. FileList', link: '/en/components/file-list' },
        { text: '169. FolderTree', link: '/en/components/folder-tree' },
        { text: '170. FolderList', link: '/en/components/folder-list' },
        { text: '171. MediaGallery', link: '/en/components/media-gallery' },
        { text: '172. ProductList', link: '/en/components/product-list' },
        { text: '173. UserList', link: '/en/components/user-list' },
        { text: '174. NotificationList', link: '/en/components/notification-list' },
        { text: '175. Watermark', link: '/en/components/watermark' },
        { text: '176. ProfileCard', link: '/en/components/profile-card' },
      ],
    },
    {
      text: 'Feedback (30)',
      collapsed: true,
      items: [
        { text: '177. Alert', link: '/en/components/alert' },
        { text: '178. Banner', link: '/en/components/banner' },
        { text: '179. Callout', link: '/en/components/callout' },
        { text: '180. Toast', link: '/en/components/toast' },
        { text: '181. Message', link: '/en/components/message' },
        { text: '182. Snackbar', link: '/en/components/snackbar' },
        { text: '183. Notification', link: '/en/components/notification' },
        { text: '184. NotificationCenter', link: '/en/components/notification-center' },
        { text: '185. Dialog', link: '/en/components/dialog' },
        { text: '186. Modal', link: '/en/components/modal' },
        { text: '187. ConfirmDialog', link: '/en/components/confirm-dialog' },
        { text: '188. PromptDialog', link: '/en/components/prompt-dialog' },
        { text: '189. FullscreenModal', link: '/en/components/fullscreen-modal' },
        { text: '190. Drawer', link: '/en/components/drawer' },
        { text: '191. BottomSheet', link: '/en/components/bottom-sheet' },
        { text: '192. Popover', link: '/en/components/popover' },
        { text: '193. Tooltip', link: '/en/components/tooltip' },
        { text: '194. HoverCard', link: '/en/components/hover-card' },
        { text: '195. ContextMenu', link: '/en/components/context-menu' },
        { text: '196. Loading', link: '/en/components/loading' },
        { text: '197. LoadingOverlay', link: '/en/components/loading-overlay' },
        { text: '198. ProgressBar', link: '/en/components/progress-bar' },
        { text: '199. SkeletonLoader', link: '/en/components/skeleton-loader' },
        { text: '200. EmptyState', link: '/en/components/empty-state' },
        { text: '201. Result', link: '/en/components/result' },
        { text: '202. ErrorPage', link: '/en/components/error-page' },
        { text: '203. Offline', link: '/en/components/offline' },
        { text: '204. Retry', link: '/en/components/retry' },
        { text: '205. Tour', link: '/en/components/tour' },
        { text: '206. Guide', link: '/en/components/guide' },
      ],
    },
    {
      text: 'Navigation (23)',
      collapsed: true,
      items: [
        { text: '207. Menu', link: '/en/components/menu' },
        { text: '208. MenuBar', link: '/en/components/menu-bar' },
        { text: '209. DropdownMenu', link: '/en/components/dropdown-menu' },
        { text: '210. MegaMenu', link: '/en/components/mega-menu' },
        { text: '211. Tabs', link: '/en/components/tabs' },
        { text: '212. TabBar', link: '/en/components/tab-bar' },
        { text: '213. Breadcrumb', link: '/en/components/breadcrumb' },
        { text: '214. Pagination', link: '/en/components/pagination' },
        { text: '215. Pager', link: '/en/components/pager' },
        { text: '216. NavBar', link: '/en/components/nav-bar' },
        { text: '217. TopNav', link: '/en/components/top-nav' },
        { text: '218. SideNav', link: '/en/components/side-nav' },
        { text: '219. BottomNav', link: '/en/components/bottom-nav' },
        { text: '220. MobileNav', link: '/en/components/mobile-nav' },
        { text: '221. CommandPalette', link: '/en/components/command-palette' },
        { text: '222. SearchBar', link: '/en/components/search-bar' },
        { text: '223. SearchDialog', link: '/en/components/search-dialog' },
        { text: '224. FilterBar', link: '/en/components/filter-bar' },
        { text: '225. SortBar', link: '/en/components/sort-bar' },
        { text: '226. CategoryNav', link: '/en/components/category-nav' },
        { text: '227. TagNav', link: '/en/components/tag-nav' },
        { text: '228. AnchorNav', link: '/en/components/anchor-nav' },
        { text: '229. FloatingMenu', link: '/en/components/floating-menu' },
      ],
    },
    {
      text: 'Media (27)',
      collapsed: true,
      items: [
        { text: '230. ImageViewer', link: '/en/components/image-viewer' },
        { text: '231. ImagePreview', link: '/en/components/image-preview' },
        { text: '232. ImageZoom', link: '/en/components/image-zoom' },
        { text: '233. ImageCropper', link: '/en/components/image-cropper' },
        { text: '234. ImageEditor', link: '/en/components/image-editor' },
        { text: '235. Gallery', link: '/en/components/gallery' },
        { text: '236. Carousel', link: '/en/components/carousel' },
        { text: '237. SliderGallery', link: '/en/components/slider-gallery' },
        { text: '238. Lightbox', link: '/en/components/lightbox' },
        { text: '239. VideoPlayer', link: '/en/components/video-player' },
        { text: '240. AudioPlayer', link: '/en/components/audio-player' },
        { text: '241. MediaPlayer', link: '/en/components/media-player' },
        { text: '242. MediaCard', link: '/en/components/media-card' },
        { text: '243. MediaGrid', link: '/en/components/media-grid' },
        { text: '244. Camera', link: '/en/components/camera' },
        { text: '245. ScreenRecorder', link: '/en/components/screen-recorder' },
        { text: '246. AudioRecorder', link: '/en/components/audio-recorder' },
        { text: '247. QRScanner', link: '/en/components/qr-scanner' },
        { text: '248. BarcodeScanner', link: '/en/components/barcode-scanner' },
        { text: '249. AvatarEditor', link: '/en/components/avatar-editor' },
        { text: '250. GifPlayer', link: '/en/components/gif-player' },
        { text: '251. LottiePlayer', link: '/en/components/lottie-player' },
        { text: '252. AnimationPlayer', link: '/en/components/animation-player' },
        { text: '253. PosterGenerator', link: '/en/components/poster-generator' },
        { text: '254. Thumbnail', link: '/en/components/thumbnail' },
        { text: '255. DocumentViewer', link: '/en/components/document-viewer' },
        { text: '256. Panorama', link: '/en/components/panorama' },
      ],
    },
    {
      text: 'Advanced (24)',
      collapsed: true,
      items: [
        { text: '257. GlobalSearch', link: '/en/components/global-search' },
        { text: '258. Spotlight', link: '/en/components/spotlight' },
        { text: '259. KanbanBoard', link: '/en/components/kanban-board' },
        { text: '260. WorkflowDesigner', link: '/en/components/workflow-designer' },
        { text: '261. FlowChart', link: '/en/components/flow-chart' },
        { text: '262. MindMap', link: '/en/components/mind-map' },
        { text: '263. OrgChart', link: '/en/components/org-chart' },
        { text: '264. TreeEditor', link: '/en/components/tree-editor' },
        { text: '265. DragList', link: '/en/components/drag-list' },
        { text: '266. DragGrid', link: '/en/components/drag-grid' },
        { text: '267. DragTree', link: '/en/components/drag-tree' },
        { text: '268. SortableList', link: '/en/components/sortable-list' },
        { text: '269. SortableTable', link: '/en/components/sortable-table' },
        { text: '270. VirtualScroller', link: '/en/components/virtual-scroller' },
        { text: '271. InfiniteScroll', link: '/en/components/infinite-scroll' },
        { text: '272. SmartTable', link: '/en/components/smart-table' },
        { text: '273. QueryBuilder', link: '/en/components/query-builder' },
        { text: '274. FilterBuilder', link: '/en/components/filter-builder' },
        { text: '275. LayoutBuilder', link: '/en/components/layout-builder' },
        { text: '276. DashboardBuilder', link: '/en/components/dashboard-builder' },
        { text: '277. PageBuilder', link: '/en/components/page-builder' },
        { text: '278. ThemeEditor', link: '/en/components/theme-editor' },
        { text: '279. ComponentPlayground', link: '/en/components/component-playground' },
        { text: '280. LiveEditor', link: '/en/components/live-editor' },
      ],
    },
    {
      text: 'Utility (20)',
      collapsed: true,
      items: [
        { text: '281. FocusTrap', link: '/en/components/focus-trap' },
        { text: '282. ClickOutside', link: '/en/components/click-outside' },
        { text: '283. ResizeObserver', link: '/en/components/resize-observer' },
        { text: '284. IntersectionObserver', link: '/en/components/intersection-observer' },
        { text: '285. ScrollLock', link: '/en/components/scroll-lock' },
        { text: '286. ScrollSpy', link: '/en/components/scroll-spy' },
        { text: '287. Keybinding', link: '/en/components/keybinding' },
        { text: '288. Hotkey', link: '/en/components/hotkey' },
        { text: '289. ClipboardManager', link: '/en/components/clipboard-manager' },
        { text: '290. Fullscreen', link: '/en/components/fullscreen' },
        { text: '291. IdleTimer', link: '/en/components/idle-timer' },
        { text: '292. VisibilitySensor', link: '/en/components/visibility-sensor' },
        { text: '293. DeviceDetector', link: '/en/components/device-detector' },
        { text: '294. ThemeProvider', link: '/en/components/theme-provider' },
        { text: '295. LocaleProvider', link: '/en/components/locale-provider' },
        { text: '296. ConfigProvider', link: '/en/components/config-provider' },
        { text: '297. ErrorBoundary', link: '/en/components/error-boundary' },
        { text: '298. RenderIf', link: '/en/components/render-if' },
        { text: '299. Breakpoint', link: '/en/components/breakpoint' },
        { text: '300. MediaQuery', link: '/en/components/media-query' },
      ],
    },
  ],
}

export default defineConfig({
  title: 'Parrot UI',
  description: '基于 uni-app X 的跨终端组件库',
  ignoreDeadLinks: true,
  rewrites: { 'zh/:rest*': ':rest*' },
  locales: {
    root: {
      label: '🇨🇳 简体中文',
      lang: 'zh-CN',
      title: 'Parrot UI',
      description: '基于 uni-app X 的跨终端组件库，支持 Android / iOS / 鸿蒙 / 微信小程序 / Web',
      themeConfig: {
        nav: [
          { text: '指南',     link: '/guide/introduction',  activeMatch: '/guide/' },
          { text: '组件',     link: '/components/overview',   activeMatch: '/components/' },
          { text: '架构',     link: '/guide/architecture' },
          { text: '更新日志', link: '/guide/changelog' },
        ],
        sidebar: {
          '/guide/': zhSidebar['/zh/guide/'].map(g => ({ ...g, items: g.items.map(i => ({ ...i, link: i.link.replace('/zh/', '/') })) })),
          '/components/': zhSidebar['/zh/components/'].map(g => ({ ...g, items: g.items.map(i => ({ ...i, link: i.link.replace('/zh/', '/') })) })),
        },
        outline: { level: [2, 3], label: '本页目录' },
        sidebarMenuLabel: '目录', returnToTopLabel: '返回顶部',
        darkModeSwitchLabel: '外观', lightModeSwitchTitle: '切换至亮色模式', darkModeSwitchTitle: '切换至暗色模式',
        editLink: { pattern: 'https://github.com/parrotui/parrotui/edit/main/docs/:path', text: '在 GitHub 上编辑此页' },
        lastUpdated: { text: '最后更新' }, docFooter: { prev: '上一页', next: '下一页' },
      },
    },
    'zh-HK': {
      label: '🇭🇰 繁體中文', lang: 'zh-HK', title: 'Parrot UI', description: '基於 uni-app X 的跨終端元件庫',
      themeConfig: {
        nav: [
          { text: '指南', link: '/zh-HK/guide/introduction', activeMatch: '/zh-HK/guide/' },
          { text: '元件', link: '/zh-HK/components/overview', activeMatch: '/zh-HK/components/' },
          { text: '架構', link: '/zh-HK/guide/architecture' },
          { text: '更新日誌', link: '/zh-HK/guide/changelog' },
        ],
        sidebar: zhTWSidebar,
        outline: { level: [2, 3], label: '本頁目錄' },
        sidebarMenuLabel: '目錄', returnToTopLabel: '返回頂部',
        darkModeSwitchLabel: '外觀', lightModeSwitchTitle: '切換至亮色模式', darkModeSwitchTitle: '切換至暗色模式',
        editLink: { pattern: 'https://github.com/parrotui/parrotui/edit/main/docs/:path', text: '在 GitHub 上編輯此頁' },
        lastUpdated: { text: '最後更新' }, docFooter: { prev: '上一頁', next: '下一頁' },
      },
    },
    en: {
      label: '🇺🇸 English', lang: 'en-US', title: 'Parrot UI', description: 'Cross-platform component library based on uni-app X',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/en/guide/introduction', activeMatch: '/en/guide/' },
          { text: 'Components', link: '/en/components/overview', activeMatch: '/en/components/' },
          { text: 'Architecture', link: '/en/guide/architecture' },
          { text: 'Changelog', link: '/en/guide/changelog' },
        ],
        sidebar: enSidebar,
        outline: { level: [2, 3], label: 'On this page' },
        sidebarMenuLabel: 'Menu', returnToTopLabel: 'Return to top',
        darkModeSwitchLabel: 'Appearance', lightModeSwitchTitle: 'Switch to light mode', darkModeSwitchTitle: 'Switch to dark mode',
        editLink: { pattern: 'https://github.com/parrotui/parrotui/edit/main/docs/:path', text: 'Edit this page on GitHub' },
        lastUpdated: { text: 'Last updated' }, docFooter: { prev: 'Previous page', next: 'Next page' },
      },
    },
  },
  base: '/',
  themeConfig: {
    logo: '/icon.svg', siteTitle: 'Parrot UI',
    socialLinks: [
      { icon: 'github', link: 'https://github.com/parrotui/parrotui' },
      { icon: { svg: weiboSvg }, link: 'https://weibo.com/parrotui', target: '_blank' },
    ],
    footer: { message: 'Released under the MIT License.', copyright: 'Copyright © 2026-present Parrot UI Contributors' },
    search: { provider: 'local' },
  },
  markdown: { lineNumbers: true },
  head: [
    ['link', { rel: 'icon', href: '/favicon.ico' }],
    ['link', { rel: 'icon', href: '/favicon-32x32.png', type: 'image/png', sizes: '32x32' }],
    ['link', { rel: 'icon', href: '/favicon-16x16.png', type: 'image/png', sizes: '16x16' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' }],
    ['link', { rel: 'manifest', href: '/site.webmanifest' }],
    ['meta', { name: 'theme-color', content: '#1a7eff' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'Parrot UI' }],
    ['meta', { property: 'og:description', content: '基于 uni-app X 的跨终端组件库' }],
    ['meta', { property: 'og:url', content: 'https://doc.parrotui.com' }],
    ['meta', { property: 'og:image', content: 'https://doc.parrotui.com/android-chrome-512x512.png' }],
  ],
})
