import { defineConfig } from 'vitepress'

// 微博官方 SVG 图标
const weiboSvg = `<svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path d="M851.4 590.193c-22.196-66.233-90.385-90.422-105.912-91.863-15.523-1.442-29.593-9.94-19.295-27.505 10.302-17.566 29.304-68.684-7.248-104.681-36.564-36.14-116.512-22.462-173.094 0.866-56.434 23.327-53.39 7.055-51.65-8.925 1.89-16.848 32.355-111.02-60.791-122.395C311.395 220.86 154.85 370.754 99.572 457.15 16 587.607 29.208 675.873 29.208 675.873h0.58c10.009 121.819 190.787 218.869 412.328 218.869 190.5 0 350.961-71.853 398.402-169.478 0 0 0.143-0.433 0.575-1.156 4.938-10.506 8.71-21.168 11.035-32.254 6.668-26.205 11.755-64.215-0.728-101.66z m-436.7 251.27c-157.71 0-285.674-84.095-285.674-187.768 0-103.671 127.82-187.76 285.674-187.76 157.705 0 285.673 84.089 285.673 187.76 0 103.815-127.968 187.768-285.673 187.768z" fill="currentColor"/><path d="M803.096 425.327c2.896 1.298 5.945 1.869 8.994 1.869 8.993 0 17.7-5.328 21.323-14.112 5.95-13.964 8.993-28.793 8.993-44.205 0-62.488-51.208-113.321-114.181-113.321-15.379 0-30.32 3.022-44.396 8.926-11.755 4.896-17.263 18.432-12.335 30.24 4.933 11.662 18.572 17.134 30.465 12.238 8.419-3.46 17.268-5.33 26.41-5.33 37.431 0 67.752 30.241 67.752 67.247 0 9.068-1.735 17.857-5.369 26.202a22.832 22.832 0 0 0 12.335 30.236z" fill="currentColor"/><path d="M726.922 114.157c-25.969 0-51.65 3.744-76.315 10.942-18.423 5.472-28.868 24.622-23.5 42.91 5.509 18.29 24.804 28.657 43.237 23.329a201.888 201.888 0 0 1 56.578-8.064c109.253 0 198.189 88.271 198.189 196.696 0 19.436-2.905 38.729-8.419 57.16-5.508 18.289 4.79 37.588 23.212 43.053 3.342 1.014 6.817 1.442 10.159 1.442 14.943 0 28.725-9.648 33.37-24.48 7.547-24.906 11.462-50.826 11.462-77.175-0.143-146.588-120.278-265.813-267.973-265.813z" fill="currentColor"/><path d="M388.294 534.47c-84.151 0-152.34 59.178-152.34 132.334 0 73.141 68.189 132.328 152.34 132.328 84.148 0 152.337-59.182 152.337-132.328 0-73.15-68.19-132.334-152.337-132.334zM338.53 752.763c-29.454 0-53.39-23.755-53.39-52.987 0-29.228 23.941-52.989 53.39-52.989 29.453 0 53.39 23.76 53.39 52.989 0 29.227-23.937 52.987-53.39 52.987z m99.82-95.465c-6.382 11.086-19.296 15.696-28.726 10.219-9.43-5.323-11.75-18.717-5.37-29.803 6.386-11.09 19.297-15.7 28.725-10.224 9.43 5.472 11.755 18.864 5.37 29.808z" fill="currentColor"/></svg>`

// 简体中文侧边栏
const zhSidebar = {
  '/zh/guide/': [
    {
      text: '开始使用',
      collapsed: false,
      items: [
        { text: '介绍',         link: '/zh/guide/introduction' },
        { text: '快速上手',     link: '/zh/guide/getting-started' },
        { text: '安装',         link: '/zh/guide/installation' },
        { text: '更新日志',     link: '/zh/guide/changelog' },
      ],
    },
    {
      text: '设计基础',
      collapsed: false,
      items: [
        { text: 'Design Tokens', link: '/zh/guide/tokens' },
        { text: '颜色系统',     link: '/zh/guide/colors' },
        { text: '字体规范',     link: '/zh/guide/typography' },
        { text: '间距规范',     link: '/zh/guide/spacing' },
        { text: '主题系统',     link: '/zh/guide/theming' },
        { text: '国际化 i18n', link: '/zh/guide/i18n' },
      ],
    },
    {
      text: '架构参考',
      collapsed: false,
      items: [
        { text: '架构概览',         link: '/zh/guide/architecture' },
        { text: 'Composables API', link: '/zh/guide/composables' },
        { text: '指令工具',         link: '/zh/guide/directives' },
        { text: '工具函数',         link: '/zh/guide/utils' },
      ],
    },
  ],
  '/zh/components/': [
    {
      text: '组件概览',
      collapsed: false,
      items: [
        { text: '组件概览', link: '/zh/components/overview' },
      ],
    },
    {
      text: '基础组件 Basic (41)',
      collapsed: true,
      items: [
        { text: 'Color 颜色', link: '/zh/components/color' },
        { text: 'Text 文本', link: '/zh/components/text' },
        { text: 'Heading 标题', link: '/zh/components/heading' },
        { text: 'Paragraph 段落', link: '/zh/components/paragraph' },
        { text: 'Label 标签文本', link: '/zh/components/label' },
        { text: 'Caption 说明文字', link: '/zh/components/caption' },
        { text: 'Code 代码块', link: '/zh/components/code' },
        { text: 'Quote 引用', link: '/zh/components/quote' },
        { text: 'Number 数字', link: '/zh/components/number' },
        { text: 'Statistic 统计数值', link: '/zh/components/statistic' },
        { text: 'Counter 动画计数器', link: '/zh/components/counter' },
        { text: 'Countdown 倒计时', link: '/zh/components/countdown' },
        { text: 'Currency 货币', link: '/zh/components/currency' },
        { text: 'Percentage 百分比', link: '/zh/components/percentage' },
        { text: 'Icon 图标', link: '/zh/components/icon' },
        { text: 'IconButton 图标按钮', link: '/zh/components/icon-button' },
        { text: 'Button 按钮', link: '/zh/components/button' },
        { text: 'ButtonGroup 按钮组', link: '/zh/components/button-group' },
        { text: 'Link 链接', link: '/zh/components/link' },
        { text: 'Divider 分割线', link: '/zh/components/divider' },
        { text: 'Spacer 间距', link: '/zh/components/spacer' },
        { text: 'Badge 徽标', link: '/zh/components/badge' },
        { text: 'Tag 标签', link: '/zh/components/tag' },
        { text: 'Chip 标签片', link: '/zh/components/chip' },
        { text: 'Avatar 头像', link: '/zh/components/avatar' },
        { text: 'AvatarGroup 头像组', link: '/zh/components/avatar-group' },
        { text: 'Image 图片', link: '/zh/components/image' },
        { text: 'Picture 图文', link: '/zh/components/picture' },
        { text: 'AspectRatio 宽高比', link: '/zh/components/aspect-ratio' },
        { text: 'Skeleton 骨架屏', link: '/zh/components/skeleton' },
        { text: 'Spinner 加载旋转', link: '/zh/components/spinner' },
        { text: 'Progress 进度条', link: '/zh/components/progress' },
        { text: 'CircularProgress 环形进度', link: '/zh/components/circular-progress' },
        { text: 'Rating 评分', link: '/zh/components/rating' },
        { text: 'Switch 开关', link: '/zh/components/switch' },
        { text: 'Slider 滑块', link: '/zh/components/slider' },
        { text: 'RangeSlider 双滑块', link: '/zh/components/range-slider' },
        { text: 'Clipboard 剪贴板', link: '/zh/components/clipboard' },
        { text: 'CopyButton 复制按钮', link: '/zh/components/copy-button' },
        { text: 'Highlight 高亮', link: '/zh/components/highlight' },
        { text: 'VisuallyHidden 视觉隐藏', link: '/zh/components/visually-hidden' },
      ],
    },
    {
      text: '布局组件 Layout (32)',
      collapsed: true,
      items: [
        { text: 'Container 容器', link: '/zh/components/container' },
        { text: 'Flex 弹性布局', link: '/zh/components/flex' },
        { text: 'Grid 网格布局', link: '/zh/components/grid' },
        { text: 'Stack 堆叠布局', link: '/zh/components/stack' },
        { text: 'HStack 水平堆叠', link: '/zh/components/h-stack' },
        { text: 'VStack 垂直堆叠', link: '/zh/components/v-stack' },
        { text: 'Center 居中容器', link: '/zh/components/center' },
        { text: 'Space 间距容器', link: '/zh/components/space' },
        { text: 'Wrap 自动换行', link: '/zh/components/wrap' },
        { text: 'DividerLayout 分割布局', link: '/zh/components/divider-layout' },
        { text: 'AspectRatioLayout 比例布局', link: '/zh/components/aspect-ratio-layout' },
        { text: 'Page 页面容器', link: '/zh/components/page' },
        { text: 'PageHeader 页头', link: '/zh/components/page-header' },
        { text: 'PageFooter 页脚', link: '/zh/components/page-footer' },
        { text: 'Section 区块', link: '/zh/components/section' },
        { text: 'Sidebar 侧边栏', link: '/zh/components/sidebar' },
        { text: 'SidebarLayout 侧边栏布局', link: '/zh/components/sidebar-layout' },
        { text: 'HeaderLayout 顶栏布局', link: '/zh/components/header-layout' },
        { text: 'FooterLayout 底栏布局', link: '/zh/components/footer-layout' },
        { text: 'SplitLayout 分栏布局', link: '/zh/components/split-layout' },
        { text: 'DashboardLayout 仪表盘布局', link: '/zh/components/dashboard-layout' },
        { text: 'CardLayout 卡片布局', link: '/zh/components/card-layout' },
        { text: 'ListLayout 列表布局', link: '/zh/components/list-layout' },
        { text: 'MediaLayout 媒体布局', link: '/zh/components/media-layout' },
        { text: 'ScrollView 滚动视图', link: '/zh/components/scroll-view' },
        { text: 'Sticky 粘性定位', link: '/zh/components/sticky' },
        { text: 'Portal 传送门', link: '/zh/components/portal' },
        { text: 'Overlay 遮罩层', link: '/zh/components/overlay' },
        { text: 'SafeArea 安全区域', link: '/zh/components/safe-area' },
        { text: 'Viewport 视口容器', link: '/zh/components/viewport' },
        { text: 'FixedLayout 固定布局', link: '/zh/components/fixed-layout' },
        { text: 'FloatingLayout 浮动布局', link: '/zh/components/floating-layout' },
      ],
    },
    {
      text: '表单组件 Form (53)',
      collapsed: true,
      items: [
        { text: 'Form 表单容器', link: '/zh/components/form' },
        { text: 'FormItem 表单项', link: '/zh/components/form-item' },
        { text: 'FormLabel 表单标签', link: '/zh/components/form-label' },
        { text: 'FormDescription 表单描述', link: '/zh/components/form-description' },
        { text: 'FormError 表单错误', link: '/zh/components/form-error' },
        { text: 'FormGroup 表单分组', link: '/zh/components/form-group' },
        { text: 'FormField 表单字段', link: '/zh/components/form-field' },
        { text: 'Input 输入框', link: '/zh/components/input' },
        { text: 'Textarea 文本域', link: '/zh/components/textarea' },
        { text: 'PasswordInput 密码输入', link: '/zh/components/password-input' },
        { text: 'NumberInput 数字输入', link: '/zh/components/number-input' },
        { text: 'OtpInput 验证码输入', link: '/zh/components/otp-input' },
        { text: 'SearchInput 搜索输入', link: '/zh/components/search-input' },
        { text: 'UrlInput 网址输入', link: '/zh/components/url-input' },
        { text: 'EmailInput 邮箱输入', link: '/zh/components/email-input' },
        { text: 'PhoneInput 电话输入', link: '/zh/components/phone-input' },
        { text: 'Select 下拉选择', link: '/zh/components/select' },
        { text: 'MultiSelect 多选下拉', link: '/zh/components/multi-select' },
        { text: 'TreeSelect 树形选择', link: '/zh/components/tree-select' },
        { text: 'Cascader 级联选择', link: '/zh/components/cascader' },
        { text: 'Checkbox 复选框', link: '/zh/components/checkbox' },
        { text: 'CheckboxGroup 复选框组', link: '/zh/components/checkbox-group' },
        { text: 'Radio 单选框', link: '/zh/components/radio' },
        { text: 'RadioGroup 单选框组', link: '/zh/components/radio-group' },
        { text: 'SwitchField 开关字段', link: '/zh/components/switch-field' },
        { text: 'SliderField 滑块字段', link: '/zh/components/slider-field' },
        { text: 'RangeSliderField 范围滑块字段', link: '/zh/components/range-slider-field' },
        { text: 'RatingField 评分字段', link: '/zh/components/rating-field' },
        { text: 'DatePicker 日期选择', link: '/zh/components/date-picker' },
        { text: 'TimePicker 时间选择', link: '/zh/components/time-picker' },
        { text: 'DateTimePicker 日期时间', link: '/zh/components/date-time-picker' },
        { text: 'RangePicker 范围选择', link: '/zh/components/range-picker' },
        { text: 'WeekPicker 周选择', link: '/zh/components/week-picker' },
        { text: 'MonthPicker 月选择', link: '/zh/components/month-picker' },
        { text: 'YearPicker 年选择', link: '/zh/components/year-picker' },
        { text: 'ColorPicker 颜色选择器', link: '/zh/components/color-picker' },
        { text: 'FileUpload 文件上传', link: '/zh/components/file-upload' },
        { text: 'ImageUpload 图片上传', link: '/zh/components/image-upload' },
        { text: 'Dropzone 拖拽上传区', link: '/zh/components/dropzone' },
        { text: 'UploadList 上传列表', link: '/zh/components/upload-list' },
        { text: 'SignaturePad 手写签名', link: '/zh/components/signature-pad' },
        { text: 'RichTextEditor 富文本编辑', link: '/zh/components/rich-text-editor' },
        { text: 'MarkdownEditor Markdown编辑', link: '/zh/components/markdown-editor' },
        { text: 'JsonEditor JSON编辑器', link: '/zh/components/json-editor' },
        { text: 'CodeEditor 代码编辑器', link: '/zh/components/code-editor' },
        { text: 'TagInput 标签输入', link: '/zh/components/tag-input' },
        { text: 'Autocomplete 自动完成', link: '/zh/components/autocomplete' },
        { text: 'Mention 提及', link: '/zh/components/mention' },
        { text: 'Transfer 穿梭框', link: '/zh/components/transfer' },
        { text: 'DualList 双列表', link: '/zh/components/dual-list' },
        { text: 'Stepper 步进器', link: '/zh/components/stepper' },
        { text: 'WizardForm 向导表单', link: '/zh/components/wizard-form' },
        { text: 'FormArray 动态表单', link: '/zh/components/form-array' },
      ],
    },
    {
      text: '数据组件 Data (18)',
      collapsed: true,
      items: [
        { text: 'Table 表格', link: '/zh/components/table' },
        { text: 'DataTable 数据表格', link: '/zh/components/data-table' },
        { text: 'VirtualTable 虚拟表格', link: '/zh/components/virtual-table' },
        { text: 'TreeTable 树形表格', link: '/zh/components/tree-table' },
        { text: 'GridTable 网格表格', link: '/zh/components/grid-table' },
        { text: 'List 列表', link: '/zh/components/list' },
        { text: 'VirtualList 虚拟列表', link: '/zh/components/virtual-list' },
        { text: 'Tree 树形控件', link: '/zh/components/tree' },
        { text: 'DataGrid 数据网格', link: '/zh/components/data-grid' },
        { text: 'StatisticCard 统计卡片', link: '/zh/components/statistic-card' },
        { text: 'Metric 指标卡', link: '/zh/components/metric' },
        { text: 'Timeline 时间线', link: '/zh/components/timeline' },
        { text: 'Calendar 日历', link: '/zh/components/calendar' },
        { text: 'Schedule 日程', link: '/zh/components/schedule' },
        { text: 'ActivityFeed 动态流', link: '/zh/components/activity-feed' },
        { text: 'Kanban 看板', link: '/zh/components/kanban' },
        { text: 'DataCard 数据卡片', link: '/zh/components/data-card' },
        { text: 'Waterfall 瀑布流', link: '/zh/components/waterfall' },
      ],
    },
    {
      text: '图表组件 Chart (14)',
      collapsed: true,
      items: [
        { text: 'Chart 图表容器', link: '/zh/components/chart' },
        { text: 'LineChart 折线图', link: '/zh/components/line-chart' },
        { text: 'BarChart 柱状图', link: '/zh/components/bar-chart' },
        { text: 'PieChart 饼图', link: '/zh/components/pie-chart' },
        { text: 'AreaChart 面积图', link: '/zh/components/area-chart' },
        { text: 'RadarChart 雷达图', link: '/zh/components/radar-chart' },
        { text: 'ScatterChart 散点图', link: '/zh/components/scatter-chart' },
        { text: 'Heatmap 热力图', link: '/zh/components/heatmap' },
        { text: 'Gauge 仪表盘', link: '/zh/components/gauge' },
        { text: 'Sparkline 迷你图', link: '/zh/components/sparkline' },
        { text: 'Map 地图', link: '/zh/components/map' },
        { text: 'GeoMap 地理地图', link: '/zh/components/geo-map' },
        { text: 'FunnelChart 漏斗图', link: '/zh/components/funnel-chart' },
        { text: 'TreemapChart 矩形树图', link: '/zh/components/treemap-chart' },
      ],
    },
    {
      text: '展示组件 Display (18)',
      collapsed: true,
      items: [
        { text: 'DataViewer 数据查看器', link: '/zh/components/data-viewer' },
        { text: 'JsonViewer JSON查看器', link: '/zh/components/json-viewer' },
        { text: 'YamlViewer YAML查看器', link: '/zh/components/yaml-viewer' },
        { text: 'KeyValue 键值对', link: '/zh/components/key-value' },
        { text: 'LogViewer 日志查看器', link: '/zh/components/log-viewer' },
        { text: 'CodeViewer 代码查看器', link: '/zh/components/code-viewer' },
        { text: 'MarkdownViewer Markdown渲染', link: '/zh/components/markdown-viewer' },
        { text: 'DiffViewer 差异对比', link: '/zh/components/diff-viewer' },
        { text: 'FileTree 文件树', link: '/zh/components/file-tree' },
        { text: 'FileList 文件列表', link: '/zh/components/file-list' },
        { text: 'FolderTree 文件夹树', link: '/zh/components/folder-tree' },
        { text: 'FolderList 文件夹列表', link: '/zh/components/folder-list' },
        { text: 'MediaGallery 媒体画廊', link: '/zh/components/media-gallery' },
        { text: 'ProductList 商品列表', link: '/zh/components/product-list' },
        { text: 'UserList 用户列表', link: '/zh/components/user-list' },
        { text: 'NotificationList 通知列表', link: '/zh/components/notification-list' },
        { text: 'Watermark 水印', link: '/zh/components/watermark' },
        { text: 'ProfileCard 个人名片', link: '/zh/components/profile-card' },
      ],
    },
    {
      text: '反馈组件 Feedback (30)',
      collapsed: true,
      items: [
        { text: 'Alert 警告提示', link: '/zh/components/alert' },
        { text: 'Banner 横幅', link: '/zh/components/banner' },
        { text: 'Callout 标注', link: '/zh/components/callout' },
        { text: 'Toast 轻提示', link: '/zh/components/toast' },
        { text: 'Message 消息提示', link: '/zh/components/message' },
        { text: 'Snackbar 操作提示', link: '/zh/components/snackbar' },
        { text: 'Notification 通知', link: '/zh/components/notification' },
        { text: 'NotificationCenter 通知中心', link: '/zh/components/notification-center' },
        { text: 'Dialog 对话框', link: '/zh/components/dialog' },
        { text: 'Modal 模态框', link: '/zh/components/modal' },
        { text: 'ConfirmDialog 确认对话框', link: '/zh/components/confirm-dialog' },
        { text: 'PromptDialog 输入对话框', link: '/zh/components/prompt-dialog' },
        { text: 'FullscreenModal 全屏模态', link: '/zh/components/fullscreen-modal' },
        { text: 'Drawer 抽屉', link: '/zh/components/drawer' },
        { text: 'BottomSheet 底部面板', link: '/zh/components/bottom-sheet' },
        { text: 'Popover 气泡卡片', link: '/zh/components/popover' },
        { text: 'Tooltip 文字提示', link: '/zh/components/tooltip' },
        { text: 'HoverCard 悬停卡片', link: '/zh/components/hover-card' },
        { text: 'ContextMenu 右键菜单', link: '/zh/components/context-menu' },
        { text: 'Loading 加载', link: '/zh/components/loading' },
        { text: 'LoadingOverlay 加载遮罩', link: '/zh/components/loading-overlay' },
        { text: 'ProgressBar 进度条', link: '/zh/components/progress-bar' },
        { text: 'SkeletonLoader 骨架加载', link: '/zh/components/skeleton-loader' },
        { text: 'EmptyState 空状态', link: '/zh/components/empty-state' },
        { text: 'Result 结果页', link: '/zh/components/result' },
        { text: 'ErrorPage 错误页', link: '/zh/components/error-page' },
        { text: 'Offline 离线提示', link: '/zh/components/offline' },
        { text: 'Retry 重试', link: '/zh/components/retry' },
        { text: 'Tour 引导', link: '/zh/components/tour' },
        { text: 'Guide 指南', link: '/zh/components/guide' },
      ],
    },
    {
      text: '导航组件 Navigation (23)',
      collapsed: true,
      items: [
        { text: 'Menu 菜单', link: '/zh/components/menu' },
        { text: 'MenuBar 菜单栏', link: '/zh/components/menu-bar' },
        { text: 'DropdownMenu 下拉菜单', link: '/zh/components/dropdown-menu' },
        { text: 'MegaMenu 超级菜单', link: '/zh/components/mega-menu' },
        { text: 'Tabs 标签页', link: '/zh/components/tabs' },
        { text: 'TabBar 标签栏', link: '/zh/components/tab-bar' },
        { text: 'Breadcrumb 面包屑', link: '/zh/components/breadcrumb' },
        { text: 'Pagination 分页', link: '/zh/components/pagination' },
        { text: 'Pager 翻页器', link: '/zh/components/pager' },
        { text: 'NavBar 导航栏', link: '/zh/components/nav-bar' },
        { text: 'TopNav 顶部导航', link: '/zh/components/top-nav' },
        { text: 'SideNav 侧边导航', link: '/zh/components/side-nav' },
        { text: 'BottomNav 底部导航', link: '/zh/components/bottom-nav' },
        { text: 'MobileNav 移动导航', link: '/zh/components/mobile-nav' },
        { text: 'CommandPalette 命令面板', link: '/zh/components/command-palette' },
        { text: 'SearchBar 搜索栏', link: '/zh/components/search-bar' },
        { text: 'SearchDialog 搜索对话框', link: '/zh/components/search-dialog' },
        { text: 'FilterBar 筛选栏', link: '/zh/components/filter-bar' },
        { text: 'SortBar 排序栏', link: '/zh/components/sort-bar' },
        { text: 'CategoryNav 分类导航', link: '/zh/components/category-nav' },
        { text: 'TagNav 标签导航', link: '/zh/components/tag-nav' },
        { text: 'AnchorNav 锚点导航', link: '/zh/components/anchor-nav' },
        { text: 'FloatingMenu 浮动菜单', link: '/zh/components/floating-menu' },
      ],
    },
    {
      text: '媒体组件 Media (27)',
      collapsed: true,
      items: [
        { text: 'ImageViewer 图片查看', link: '/zh/components/image-viewer' },
        { text: 'ImagePreview 图片预览', link: '/zh/components/image-preview' },
        { text: 'ImageZoom 图片缩放', link: '/zh/components/image-zoom' },
        { text: 'ImageCropper 图片裁剪', link: '/zh/components/image-cropper' },
        { text: 'ImageEditor 图片编辑', link: '/zh/components/image-editor' },
        { text: 'Gallery 图库', link: '/zh/components/gallery' },
        { text: 'Carousel 走马灯', link: '/zh/components/carousel' },
        { text: 'SliderGallery 滑动画廊', link: '/zh/components/slider-gallery' },
        { text: 'Lightbox 灯箱', link: '/zh/components/lightbox' },
        { text: 'VideoPlayer 视频播放器', link: '/zh/components/video-player' },
        { text: 'AudioPlayer 音频播放器', link: '/zh/components/audio-player' },
        { text: 'MediaPlayer 媒体播放器', link: '/zh/components/media-player' },
        { text: 'MediaCard 媒体卡片', link: '/zh/components/media-card' },
        { text: 'MediaGrid 媒体网格', link: '/zh/components/media-grid' },
        { text: 'Camera 相机', link: '/zh/components/camera' },
        { text: 'ScreenRecorder 录屏', link: '/zh/components/screen-recorder' },
        { text: 'AudioRecorder 录音', link: '/zh/components/audio-recorder' },
        { text: 'QRScanner 二维码扫描', link: '/zh/components/qr-scanner' },
        { text: 'BarcodeScanner 条码扫描', link: '/zh/components/barcode-scanner' },
        { text: 'AvatarEditor 头像编辑', link: '/zh/components/avatar-editor' },
        { text: 'GifPlayer GIF播放', link: '/zh/components/gif-player' },
        { text: 'LottiePlayer Lottie播放', link: '/zh/components/lottie-player' },
        { text: 'AnimationPlayer 动画播放', link: '/zh/components/animation-player' },
        { text: 'PosterGenerator 海报生成', link: '/zh/components/poster-generator' },
        { text: 'Thumbnail 缩略图', link: '/zh/components/thumbnail' },
        { text: 'DocumentViewer 文档预览', link: '/zh/components/document-viewer' },
        { text: 'Panorama 全景', link: '/zh/components/panorama' },
      ],
    },
    {
      text: '高级组件 Advanced (24)',
      collapsed: true,
      items: [
        { text: 'GlobalSearch 全局搜索', link: '/zh/components/global-search' },
        { text: 'Spotlight 聚光灯', link: '/zh/components/spotlight' },
        { text: 'KanbanBoard 看板面板', link: '/zh/components/kanban-board' },
        { text: 'WorkflowDesigner 工作流设计器', link: '/zh/components/workflow-designer' },
        { text: 'FlowChart 流程图', link: '/zh/components/flow-chart' },
        { text: 'MindMap 思维导图', link: '/zh/components/mind-map' },
        { text: 'OrgChart 组织架构图', link: '/zh/components/org-chart' },
        { text: 'TreeEditor 树编辑器', link: '/zh/components/tree-editor' },
        { text: 'DragList 拖拽列表', link: '/zh/components/drag-list' },
        { text: 'DragGrid 拖拽网格', link: '/zh/components/drag-grid' },
        { text: 'DragTree 拖拽树', link: '/zh/components/drag-tree' },
        { text: 'SortableList 可排序列表', link: '/zh/components/sortable-list' },
        { text: 'SortableTable 可排序表格', link: '/zh/components/sortable-table' },
        { text: 'VirtualScroller 虚拟滚动', link: '/zh/components/virtual-scroller' },
        { text: 'InfiniteScroll 无限滚动', link: '/zh/components/infinite-scroll' },
        { text: 'SmartTable 智能表格', link: '/zh/components/smart-table' },
        { text: 'QueryBuilder 查询构建器', link: '/zh/components/query-builder' },
        { text: 'FilterBuilder 筛选构建器', link: '/zh/components/filter-builder' },
        { text: 'LayoutBuilder 布局构建器', link: '/zh/components/layout-builder' },
        { text: 'DashboardBuilder 仪表盘构建器', link: '/zh/components/dashboard-builder' },
        { text: 'PageBuilder 页面构建器', link: '/zh/components/page-builder' },
        { text: 'ThemeEditor 主题编辑器', link: '/zh/components/theme-editor' },
        { text: 'ComponentPlayground 组件演练场', link: '/zh/components/component-playground' },
        { text: 'LiveEditor 实时编辑器', link: '/zh/components/live-editor' },
      ],
    },
    {
      text: '工具组件 Utility (20)',
      collapsed: true,
      items: [
        { text: 'FocusTrap 焦点陷阱', link: '/zh/components/focus-trap' },
        { text: 'ClickOutside 外部点击', link: '/zh/components/click-outside' },
        { text: 'ResizeObserver 尺寸监听', link: '/zh/components/resize-observer' },
        { text: 'IntersectionObserver 交叉监听', link: '/zh/components/intersection-observer' },
        { text: 'ScrollLock 滚动锁定', link: '/zh/components/scroll-lock' },
        { text: 'ScrollSpy 滚动监听', link: '/zh/components/scroll-spy' },
        { text: 'Keybinding 快捷键绑定', link: '/zh/components/keybinding' },
        { text: 'Hotkey 热键', link: '/zh/components/hotkey' },
        { text: 'ClipboardManager 剪贴板管理', link: '/zh/components/clipboard-manager' },
        { text: 'Fullscreen 全屏', link: '/zh/components/fullscreen' },
        { text: 'IdleTimer 空闲计时', link: '/zh/components/idle-timer' },
        { text: 'VisibilitySensor 可见性传感', link: '/zh/components/visibility-sensor' },
        { text: 'DeviceDetector 设备检测', link: '/zh/components/device-detector' },
        { text: 'ThemeProvider 主题提供者', link: '/zh/components/theme-provider' },
        { text: 'LocaleProvider 语言提供者', link: '/zh/components/locale-provider' },
        { text: 'ConfigProvider 配置提供者', link: '/zh/components/config-provider' },
        { text: 'ErrorBoundary 错误边界', link: '/zh/components/error-boundary' },
        { text: 'RenderIf 条件渲染', link: '/zh/components/render-if' },
        { text: 'Breakpoint 断点检测', link: '/zh/components/breakpoint' },
        { text: 'MediaQuery 媒体查询', link: '/zh/components/media-query' },
      ],
    },
  ],
}

// 繁体中文侧边栏
const zhTWSidebar = {
  '/zh-HK/guide/': [
    {
      text: '開始使用',
      collapsed: false,
      items: [
        { text: '介紹',     link: '/zh-HK/guide/introduction' },
        { text: '快速上手', link: '/zh-HK/guide/getting-started' },
        { text: '安裝',     link: '/zh-HK/guide/installation' },
        { text: '更新日誌', link: '/zh-HK/guide/changelog' },
      ],
    },
    {
      text: '設計基礎',
      collapsed: false,
      items: [
        { text: 'Design Tokens', link: '/zh-HK/guide/tokens' },
        { text: '顏色系統',     link: '/zh-HK/guide/colors' },
        { text: '字體規範',     link: '/zh-HK/guide/typography' },
        { text: '間距規範',     link: '/zh-HK/guide/spacing' },
        { text: '主題系統',     link: '/zh-HK/guide/theming' },
      ],
    },
  ],
  '/zh-HK/components/': [
    {
      text: '元件概覽',
      collapsed: false,
      items: [
        { text: '元件概覽', link: '/zh-HK/components/overview' },
      ],
    },
    {
      text: '基礎元件 Basic (41)',
      collapsed: true,
      items: [
        { text: 'Color 顏色', link: '/zh-HK/components/color' },
        { text: 'Text 文字', link: '/zh-HK/components/text' },
        { text: 'Heading 標題', link: '/zh-HK/components/heading' },
        { text: 'Paragraph 段落', link: '/zh-HK/components/paragraph' },
        { text: 'Label 標籤文字', link: '/zh-HK/components/label' },
        { text: 'Caption 說明文字', link: '/zh-HK/components/caption' },
        { text: 'Code 程式碼區塊', link: '/zh-HK/components/code' },
        { text: 'Quote 引用', link: '/zh-HK/components/quote' },
        { text: 'Number 數字', link: '/zh-HK/components/number' },
        { text: 'Statistic 統計數值', link: '/zh-HK/components/statistic' },
        { text: 'Counter 動畫計數器', link: '/zh-HK/components/counter' },
        { text: 'Countdown 倒數計時', link: '/zh-HK/components/countdown' },
        { text: 'Currency 貨幣', link: '/zh-HK/components/currency' },
        { text: 'Percentage 百分比', link: '/zh-HK/components/percentage' },
        { text: 'Icon 圖示', link: '/zh-HK/components/icon' },
        { text: 'IconButton 圖示按鈕', link: '/zh-HK/components/icon-button' },
        { text: 'Button 按鈕', link: '/zh-HK/components/button' },
        { text: 'ButtonGroup 按鈕組', link: '/zh-HK/components/button-group' },
        { text: 'Link 連結', link: '/zh-HK/components/link' },
        { text: 'Divider 分割線', link: '/zh-HK/components/divider' },
        { text: 'Spacer 間距', link: '/zh-HK/components/spacer' },
        { text: 'Badge 徽標', link: '/zh-HK/components/badge' },
        { text: 'Tag 標籤', link: '/zh-HK/components/tag' },
        { text: 'Chip 標籤片', link: '/zh-HK/components/chip' },
        { text: 'Avatar 頭像', link: '/zh-HK/components/avatar' },
        { text: 'AvatarGroup 頭像組', link: '/zh-HK/components/avatar-group' },
        { text: 'Image 圖片', link: '/zh-HK/components/image' },
        { text: 'Picture 圖文', link: '/zh-HK/components/picture' },
        { text: 'AspectRatio 寬高比', link: '/zh-HK/components/aspect-ratio' },
        { text: 'Skeleton 骨架屏', link: '/zh-HK/components/skeleton' },
        { text: 'Spinner 載入旋轉', link: '/zh-HK/components/spinner' },
        { text: 'Progress 進度條', link: '/zh-HK/components/progress' },
        { text: 'CircularProgress 環形進度', link: '/zh-HK/components/circular-progress' },
        { text: 'Rating 評分', link: '/zh-HK/components/rating' },
        { text: 'Switch 開關', link: '/zh-HK/components/switch' },
        { text: 'Slider 滑塊', link: '/zh-HK/components/slider' },
        { text: 'RangeSlider 雙滑塊', link: '/zh-HK/components/range-slider' },
        { text: 'Clipboard 剪貼簿', link: '/zh-HK/components/clipboard' },
        { text: 'CopyButton 複製按鈕', link: '/zh-HK/components/copy-button' },
        { text: 'Highlight 高亮', link: '/zh-HK/components/highlight' },
        { text: 'VisuallyHidden 視覺隱藏', link: '/zh-HK/components/visually-hidden' },
      ],
    },
    {
      text: '佈局元件 Layout (32)',
      collapsed: true,
      items: [
        { text: 'Container 容器', link: '/zh-HK/components/container' },
        { text: 'Flex 彈性佈局', link: '/zh-HK/components/flex' },
        { text: 'Grid 網格佈局', link: '/zh-HK/components/grid' },
        { text: 'Stack 堆疊佈局', link: '/zh-HK/components/stack' },
        { text: 'HStack 水平堆疊', link: '/zh-HK/components/h-stack' },
        { text: 'VStack 垂直堆疊', link: '/zh-HK/components/v-stack' },
        { text: 'Center 置中容器', link: '/zh-HK/components/center' },
        { text: 'Space 間距容器', link: '/zh-HK/components/space' },
        { text: 'Wrap 自動換行', link: '/zh-HK/components/wrap' },
        { text: 'DividerLayout 分割佈局', link: '/zh-HK/components/divider-layout' },
        { text: 'AspectRatioLayout 比例佈局', link: '/zh-HK/components/aspect-ratio-layout' },
        { text: 'Page 頁面容器', link: '/zh-HK/components/page' },
        { text: 'PageHeader 頁首', link: '/zh-HK/components/page-header' },
        { text: 'PageFooter 頁尾', link: '/zh-HK/components/page-footer' },
        { text: 'Section 區塊', link: '/zh-HK/components/section' },
        { text: 'Sidebar 側邊欄', link: '/zh-HK/components/sidebar' },
        { text: 'SidebarLayout 側邊欄佈局', link: '/zh-HK/components/sidebar-layout' },
        { text: 'HeaderLayout 頂欄佈局', link: '/zh-HK/components/header-layout' },
        { text: 'FooterLayout 底欄佈局', link: '/zh-HK/components/footer-layout' },
        { text: 'SplitLayout 分欄佈局', link: '/zh-HK/components/split-layout' },
        { text: 'DashboardLayout 儀表盤佈局', link: '/zh-HK/components/dashboard-layout' },
        { text: 'CardLayout 卡片佈局', link: '/zh-HK/components/card-layout' },
        { text: 'ListLayout 列表佈局', link: '/zh-HK/components/list-layout' },
        { text: 'MediaLayout 媒體佈局', link: '/zh-HK/components/media-layout' },
        { text: 'ScrollView 捲動視圖', link: '/zh-HK/components/scroll-view' },
        { text: 'Sticky 黏性定位', link: '/zh-HK/components/sticky' },
        { text: 'Portal 傳送門', link: '/zh-HK/components/portal' },
        { text: 'Overlay 遮罩層', link: '/zh-HK/components/overlay' },
        { text: 'SafeArea 安全區域', link: '/zh-HK/components/safe-area' },
        { text: 'Viewport 視口容器', link: '/zh-HK/components/viewport' },
        { text: 'FixedLayout 固定佈局', link: '/zh-HK/components/fixed-layout' },
        { text: 'FloatingLayout 浮動佈局', link: '/zh-HK/components/floating-layout' },
      ],
    },
    {
      text: '表單元件 Form (53)',
      collapsed: true,
      items: [
        { text: 'Form 表單容器', link: '/zh-HK/components/form' },
        { text: 'FormItem 表單項', link: '/zh-HK/components/form-item' },
        { text: 'FormLabel 表單標籤', link: '/zh-HK/components/form-label' },
        { text: 'FormDescription 表單描述', link: '/zh-HK/components/form-description' },
        { text: 'FormError 表單錯誤', link: '/zh-HK/components/form-error' },
        { text: 'FormGroup 表單分組', link: '/zh-HK/components/form-group' },
        { text: 'FormField 表單欄位', link: '/zh-HK/components/form-field' },
        { text: 'Input 輸入框', link: '/zh-HK/components/input' },
        { text: 'Textarea 文字域', link: '/zh-HK/components/textarea' },
        { text: 'PasswordInput 密碼輸入', link: '/zh-HK/components/password-input' },
        { text: 'NumberInput 數字輸入', link: '/zh-HK/components/number-input' },
        { text: 'OtpInput 驗證碼輸入', link: '/zh-HK/components/otp-input' },
        { text: 'SearchInput 搜尋輸入', link: '/zh-HK/components/search-input' },
        { text: 'UrlInput 網址輸入', link: '/zh-HK/components/url-input' },
        { text: 'EmailInput 郵箱輸入', link: '/zh-HK/components/email-input' },
        { text: 'PhoneInput 電話輸入', link: '/zh-HK/components/phone-input' },
        { text: 'Select 下拉選擇', link: '/zh-HK/components/select' },
        { text: 'MultiSelect 多選下拉', link: '/zh-HK/components/multi-select' },
        { text: 'TreeSelect 樹形選擇', link: '/zh-HK/components/tree-select' },
        { text: 'Cascader 級聯選擇', link: '/zh-HK/components/cascader' },
        { text: 'Checkbox 複選框', link: '/zh-HK/components/checkbox' },
        { text: 'CheckboxGroup 複選框組', link: '/zh-HK/components/checkbox-group' },
        { text: 'Radio 單選框', link: '/zh-HK/components/radio' },
        { text: 'RadioGroup 單選框組', link: '/zh-HK/components/radio-group' },
        { text: 'SwitchField 開關欄位', link: '/zh-HK/components/switch-field' },
        { text: 'SliderField 滑塊欄位', link: '/zh-HK/components/slider-field' },
        { text: 'RangeSliderField 範圍滑塊欄位', link: '/zh-HK/components/range-slider-field' },
        { text: 'RatingField 評分欄位', link: '/zh-HK/components/rating-field' },
        { text: 'DatePicker 日期選擇', link: '/zh-HK/components/date-picker' },
        { text: 'TimePicker 時間選擇', link: '/zh-HK/components/time-picker' },
        { text: 'DateTimePicker 日期時間', link: '/zh-HK/components/date-time-picker' },
        { text: 'RangePicker 範圍選擇', link: '/zh-HK/components/range-picker' },
        { text: 'WeekPicker 週選擇', link: '/zh-HK/components/week-picker' },
        { text: 'MonthPicker 月選擇', link: '/zh-HK/components/month-picker' },
        { text: 'YearPicker 年選擇', link: '/zh-HK/components/year-picker' },
        { text: 'ColorPicker 顏色選擇器', link: '/zh-HK/components/color-picker' },
        { text: 'FileUpload 檔案上傳', link: '/zh-HK/components/file-upload' },
        { text: 'ImageUpload 圖片上傳', link: '/zh-HK/components/image-upload' },
        { text: 'Dropzone 拖拽上傳區', link: '/zh-HK/components/dropzone' },
        { text: 'UploadList 上傳列表', link: '/zh-HK/components/upload-list' },
        { text: 'SignaturePad 手寫簽名', link: '/zh-HK/components/signature-pad' },
        { text: 'RichTextEditor 富文字編輯', link: '/zh-HK/components/rich-text-editor' },
        { text: 'MarkdownEditor Markdown編輯', link: '/zh-HK/components/markdown-editor' },
        { text: 'JsonEditor JSON編輯器', link: '/zh-HK/components/json-editor' },
        { text: 'CodeEditor 程式碼編輯器', link: '/zh-HK/components/code-editor' },
        { text: 'TagInput 標籤輸入', link: '/zh-HK/components/tag-input' },
        { text: 'Autocomplete 自動完成', link: '/zh-HK/components/autocomplete' },
        { text: 'Mention 提及', link: '/zh-HK/components/mention' },
        { text: 'Transfer 穿梭框', link: '/zh-HK/components/transfer' },
        { text: 'DualList 雙列表', link: '/zh-HK/components/dual-list' },
        { text: 'Stepper 步進器', link: '/zh-HK/components/stepper' },
        { text: 'WizardForm 嚮導表單', link: '/zh-HK/components/wizard-form' },
        { text: 'FormArray 動態表單', link: '/zh-HK/components/form-array' },
      ],
    },
    {
      text: '數據元件 Data (18)',
      collapsed: true,
      items: [
        { text: 'Table 表格', link: '/zh-HK/components/table' },
        { text: 'DataTable 數據表格', link: '/zh-HK/components/data-table' },
        { text: 'VirtualTable 虛擬表格', link: '/zh-HK/components/virtual-table' },
        { text: 'TreeTable 樹形表格', link: '/zh-HK/components/tree-table' },
        { text: 'GridTable 網格表格', link: '/zh-HK/components/grid-table' },
        { text: 'List 列表', link: '/zh-HK/components/list' },
        { text: 'VirtualList 虛擬列表', link: '/zh-HK/components/virtual-list' },
        { text: 'Tree 樹形控件', link: '/zh-HK/components/tree' },
        { text: 'DataGrid 數據網格', link: '/zh-HK/components/data-grid' },
        { text: 'StatisticCard 統計卡片', link: '/zh-HK/components/statistic-card' },
        { text: 'Metric 指標卡', link: '/zh-HK/components/metric' },
        { text: 'Timeline 時間線', link: '/zh-HK/components/timeline' },
        { text: 'Calendar 日曆', link: '/zh-HK/components/calendar' },
        { text: 'Schedule 日程', link: '/zh-HK/components/schedule' },
        { text: 'ActivityFeed 動態流', link: '/zh-HK/components/activity-feed' },
        { text: 'Kanban 看板', link: '/zh-HK/components/kanban' },
        { text: 'DataCard 數據卡片', link: '/zh-HK/components/data-card' },
        { text: 'Waterfall 瀑布流', link: '/zh-HK/components/waterfall' },
      ],
    },
    {
      text: '圖表元件 Chart (14)',
      collapsed: true,
      items: [
        { text: 'Chart 圖表容器', link: '/zh-HK/components/chart' },
        { text: 'LineChart 折線圖', link: '/zh-HK/components/line-chart' },
        { text: 'BarChart 柱狀圖', link: '/zh-HK/components/bar-chart' },
        { text: 'PieChart 餅圖', link: '/zh-HK/components/pie-chart' },
        { text: 'AreaChart 面積圖', link: '/zh-HK/components/area-chart' },
        { text: 'RadarChart 雷達圖', link: '/zh-HK/components/radar-chart' },
        { text: 'ScatterChart 散點圖', link: '/zh-HK/components/scatter-chart' },
        { text: 'Heatmap 熱力圖', link: '/zh-HK/components/heatmap' },
        { text: 'Gauge 儀表盤', link: '/zh-HK/components/gauge' },
        { text: 'Sparkline 迷你圖', link: '/zh-HK/components/sparkline' },
        { text: 'Map 地圖', link: '/zh-HK/components/map' },
        { text: 'GeoMap 地理地圖', link: '/zh-HK/components/geo-map' },
        { text: 'FunnelChart 漏斗圖', link: '/zh-HK/components/funnel-chart' },
        { text: 'TreemapChart 矩形樹圖', link: '/zh-HK/components/treemap-chart' },
      ],
    },
    {
      text: '展示元件 Display (18)',
      collapsed: true,
      items: [
        { text: 'DataViewer 數據查看器', link: '/zh-HK/components/data-viewer' },
        { text: 'JsonViewer JSON查看器', link: '/zh-HK/components/json-viewer' },
        { text: 'YamlViewer YAML查看器', link: '/zh-HK/components/yaml-viewer' },
        { text: 'KeyValue 鍵值對', link: '/zh-HK/components/key-value' },
        { text: 'LogViewer 日誌查看器', link: '/zh-HK/components/log-viewer' },
        { text: 'CodeViewer 程式碼查看器', link: '/zh-HK/components/code-viewer' },
        { text: 'MarkdownViewer Markdown渲染', link: '/zh-HK/components/markdown-viewer' },
        { text: 'DiffViewer 差異對比', link: '/zh-HK/components/diff-viewer' },
        { text: 'FileTree 檔案樹', link: '/zh-HK/components/file-tree' },
        { text: 'FileList 檔案列表', link: '/zh-HK/components/file-list' },
        { text: 'FolderTree 資料夾樹', link: '/zh-HK/components/folder-tree' },
        { text: 'FolderList 資料夾列表', link: '/zh-HK/components/folder-list' },
        { text: 'MediaGallery 媒體畫廊', link: '/zh-HK/components/media-gallery' },
        { text: 'ProductList 商品列表', link: '/zh-HK/components/product-list' },
        { text: 'UserList 用戶列表', link: '/zh-HK/components/user-list' },
        { text: 'NotificationList 通知列表', link: '/zh-HK/components/notification-list' },
        { text: 'Watermark 浮水印', link: '/zh-HK/components/watermark' },
        { text: 'ProfileCard 個人名片', link: '/zh-HK/components/profile-card' },
      ],
    },
    {
      text: '回饋元件 Feedback (30)',
      collapsed: true,
      items: [
        { text: 'Alert 警告提示', link: '/zh-HK/components/alert' },
        { text: 'Banner 橫幅', link: '/zh-HK/components/banner' },
        { text: 'Callout 標註', link: '/zh-HK/components/callout' },
        { text: 'Toast 輕提示', link: '/zh-HK/components/toast' },
        { text: 'Message 訊息提示', link: '/zh-HK/components/message' },
        { text: 'Snackbar 操作提示', link: '/zh-HK/components/snackbar' },
        { text: 'Notification 通知', link: '/zh-HK/components/notification' },
        { text: 'NotificationCenter 通知中心', link: '/zh-HK/components/notification-center' },
        { text: 'Dialog 對話框', link: '/zh-HK/components/dialog' },
        { text: 'Modal 模態框', link: '/zh-HK/components/modal' },
        { text: 'ConfirmDialog 確認對話框', link: '/zh-HK/components/confirm-dialog' },
        { text: 'PromptDialog 輸入對話框', link: '/zh-HK/components/prompt-dialog' },
        { text: 'FullscreenModal 全螢幕模態', link: '/zh-HK/components/fullscreen-modal' },
        { text: 'Drawer 抽屜', link: '/zh-HK/components/drawer' },
        { text: 'BottomSheet 底部面板', link: '/zh-HK/components/bottom-sheet' },
        { text: 'Popover 氣泡卡片', link: '/zh-HK/components/popover' },
        { text: 'Tooltip 文字提示', link: '/zh-HK/components/tooltip' },
        { text: 'HoverCard 懸停卡片', link: '/zh-HK/components/hover-card' },
        { text: 'ContextMenu 右鍵選單', link: '/zh-HK/components/context-menu' },
        { text: 'Loading 載入', link: '/zh-HK/components/loading' },
        { text: 'LoadingOverlay 載入遮罩', link: '/zh-HK/components/loading-overlay' },
        { text: 'ProgressBar 進度條', link: '/zh-HK/components/progress-bar' },
        { text: 'SkeletonLoader 骨架載入', link: '/zh-HK/components/skeleton-loader' },
        { text: 'EmptyState 空狀態', link: '/zh-HK/components/empty-state' },
        { text: 'Result 結果頁', link: '/zh-HK/components/result' },
        { text: 'ErrorPage 錯誤頁', link: '/zh-HK/components/error-page' },
        { text: 'Offline 離線提示', link: '/zh-HK/components/offline' },
        { text: 'Retry 重試', link: '/zh-HK/components/retry' },
        { text: 'Tour 引導', link: '/zh-HK/components/tour' },
        { text: 'Guide 指南', link: '/zh-HK/components/guide' },
      ],
    },
    {
      text: '導航元件 Navigation (23)',
      collapsed: true,
      items: [
        { text: 'Menu 選單', link: '/zh-HK/components/menu' },
        { text: 'MenuBar 選單列', link: '/zh-HK/components/menu-bar' },
        { text: 'DropdownMenu 下拉選單', link: '/zh-HK/components/dropdown-menu' },
        { text: 'MegaMenu 超級選單', link: '/zh-HK/components/mega-menu' },
        { text: 'Tabs 標籤頁', link: '/zh-HK/components/tabs' },
        { text: 'TabBar 標籤列', link: '/zh-HK/components/tab-bar' },
        { text: 'Breadcrumb 麵包屑', link: '/zh-HK/components/breadcrumb' },
        { text: 'Pagination 分頁', link: '/zh-HK/components/pagination' },
        { text: 'Pager 翻頁器', link: '/zh-HK/components/pager' },
        { text: 'NavBar 導航列', link: '/zh-HK/components/nav-bar' },
        { text: 'TopNav 頂部導航', link: '/zh-HK/components/top-nav' },
        { text: 'SideNav 側邊導航', link: '/zh-HK/components/side-nav' },
        { text: 'BottomNav 底部導航', link: '/zh-HK/components/bottom-nav' },
        { text: 'MobileNav 行動導航', link: '/zh-HK/components/mobile-nav' },
        { text: 'CommandPalette 命令面板', link: '/zh-HK/components/command-palette' },
        { text: 'SearchBar 搜尋列', link: '/zh-HK/components/search-bar' },
        { text: 'SearchDialog 搜尋對話框', link: '/zh-HK/components/search-dialog' },
        { text: 'FilterBar 篩選列', link: '/zh-HK/components/filter-bar' },
        { text: 'SortBar 排序列', link: '/zh-HK/components/sort-bar' },
        { text: 'CategoryNav 分類導航', link: '/zh-HK/components/category-nav' },
        { text: 'TagNav 標籤導航', link: '/zh-HK/components/tag-nav' },
        { text: 'AnchorNav 錨點導航', link: '/zh-HK/components/anchor-nav' },
        { text: 'FloatingMenu 浮動選單', link: '/zh-HK/components/floating-menu' },
      ],
    },
    {
      text: '媒體元件 Media (27)',
      collapsed: true,
      items: [
        { text: 'ImageViewer 圖片查看', link: '/zh-HK/components/image-viewer' },
        { text: 'ImagePreview 圖片預覽', link: '/zh-HK/components/image-preview' },
        { text: 'ImageZoom 圖片縮放', link: '/zh-HK/components/image-zoom' },
        { text: 'ImageCropper 圖片裁剪', link: '/zh-HK/components/image-cropper' },
        { text: 'ImageEditor 圖片編輯', link: '/zh-HK/components/image-editor' },
        { text: 'Gallery 圖庫', link: '/zh-HK/components/gallery' },
        { text: 'Carousel 走馬燈', link: '/zh-HK/components/carousel' },
        { text: 'SliderGallery 滑動畫廊', link: '/zh-HK/components/slider-gallery' },
        { text: 'Lightbox 燈箱', link: '/zh-HK/components/lightbox' },
        { text: 'VideoPlayer 影片播放器', link: '/zh-HK/components/video-player' },
        { text: 'AudioPlayer 音訊播放器', link: '/zh-HK/components/audio-player' },
        { text: 'MediaPlayer 媒體播放器', link: '/zh-HK/components/media-player' },
        { text: 'MediaCard 媒體卡片', link: '/zh-HK/components/media-card' },
        { text: 'MediaGrid 媒體網格', link: '/zh-HK/components/media-grid' },
        { text: 'Camera 相機', link: '/zh-HK/components/camera' },
        { text: 'ScreenRecorder 錄屏', link: '/zh-HK/components/screen-recorder' },
        { text: 'AudioRecorder 錄音', link: '/zh-HK/components/audio-recorder' },
        { text: 'QRScanner 二維碼掃描', link: '/zh-HK/components/qr-scanner' },
        { text: 'BarcodeScanner 條碼掃描', link: '/zh-HK/components/barcode-scanner' },
        { text: 'AvatarEditor 頭像編輯', link: '/zh-HK/components/avatar-editor' },
        { text: 'GifPlayer GIF播放', link: '/zh-HK/components/gif-player' },
        { text: 'LottiePlayer Lottie播放', link: '/zh-HK/components/lottie-player' },
        { text: 'AnimationPlayer 動畫播放', link: '/zh-HK/components/animation-player' },
        { text: 'PosterGenerator 海報生成', link: '/zh-HK/components/poster-generator' },
        { text: 'Thumbnail 縮圖', link: '/zh-HK/components/thumbnail' },
        { text: 'DocumentViewer 文件預覽', link: '/zh-HK/components/document-viewer' },
        { text: 'Panorama 全景', link: '/zh-HK/components/panorama' },
      ],
    },
    {
      text: '進階元件 Advanced (24)',
      collapsed: true,
      items: [
        { text: 'GlobalSearch 全域搜尋', link: '/zh-HK/components/global-search' },
        { text: 'Spotlight 聚光燈', link: '/zh-HK/components/spotlight' },
        { text: 'KanbanBoard 看板面板', link: '/zh-HK/components/kanban-board' },
        { text: 'WorkflowDesigner 工作流設計器', link: '/zh-HK/components/workflow-designer' },
        { text: 'FlowChart 流程圖', link: '/zh-HK/components/flow-chart' },
        { text: 'MindMap 心智圖', link: '/zh-HK/components/mind-map' },
        { text: 'OrgChart 組織架構圖', link: '/zh-HK/components/org-chart' },
        { text: 'TreeEditor 樹編輯器', link: '/zh-HK/components/tree-editor' },
        { text: 'DragList 拖拽列表', link: '/zh-HK/components/drag-list' },
        { text: 'DragGrid 拖拽網格', link: '/zh-HK/components/drag-grid' },
        { text: 'DragTree 拖拽樹', link: '/zh-HK/components/drag-tree' },
        { text: 'SortableList 可排序列表', link: '/zh-HK/components/sortable-list' },
        { text: 'SortableTable 可排序表格', link: '/zh-HK/components/sortable-table' },
        { text: 'VirtualScroller 虛擬捲動', link: '/zh-HK/components/virtual-scroller' },
        { text: 'InfiniteScroll 無限捲動', link: '/zh-HK/components/infinite-scroll' },
        { text: 'SmartTable 智慧表格', link: '/zh-HK/components/smart-table' },
        { text: 'QueryBuilder 查詢建構器', link: '/zh-HK/components/query-builder' },
        { text: 'FilterBuilder 篩選建構器', link: '/zh-HK/components/filter-builder' },
        { text: 'LayoutBuilder 佈局建構器', link: '/zh-HK/components/layout-builder' },
        { text: 'DashboardBuilder 儀表盤建構器', link: '/zh-HK/components/dashboard-builder' },
        { text: 'PageBuilder 頁面建構器', link: '/zh-HK/components/page-builder' },
        { text: 'ThemeEditor 主題編輯器', link: '/zh-HK/components/theme-editor' },
        { text: 'ComponentPlayground 元件演練場', link: '/zh-HK/components/component-playground' },
        { text: 'LiveEditor 即時編輯器', link: '/zh-HK/components/live-editor' },
      ],
    },
    {
      text: '工具元件 Utility (20)',
      collapsed: true,
      items: [
        { text: 'FocusTrap 焦點陷阱', link: '/zh-HK/components/focus-trap' },
        { text: 'ClickOutside 外部點擊', link: '/zh-HK/components/click-outside' },
        { text: 'ResizeObserver 尺寸監聽', link: '/zh-HK/components/resize-observer' },
        { text: 'IntersectionObserver 交叉監聽', link: '/zh-HK/components/intersection-observer' },
        { text: 'ScrollLock 捲動鎖定', link: '/zh-HK/components/scroll-lock' },
        { text: 'ScrollSpy 捲動監聽', link: '/zh-HK/components/scroll-spy' },
        { text: 'Keybinding 快捷鍵綁定', link: '/zh-HK/components/keybinding' },
        { text: 'Hotkey 熱鍵', link: '/zh-HK/components/hotkey' },
        { text: 'ClipboardManager 剪貼簿管理', link: '/zh-HK/components/clipboard-manager' },
        { text: 'Fullscreen 全螢幕', link: '/zh-HK/components/fullscreen' },
        { text: 'IdleTimer 閒置計時', link: '/zh-HK/components/idle-timer' },
        { text: 'VisibilitySensor 可見性偵測', link: '/zh-HK/components/visibility-sensor' },
        { text: 'DeviceDetector 裝置偵測', link: '/zh-HK/components/device-detector' },
        { text: 'ThemeProvider 主題提供者', link: '/zh-HK/components/theme-provider' },
        { text: 'LocaleProvider 語言提供者', link: '/zh-HK/components/locale-provider' },
        { text: 'ConfigProvider 配置提供者', link: '/zh-HK/components/config-provider' },
        { text: 'ErrorBoundary 錯誤邊界', link: '/zh-HK/components/error-boundary' },
        { text: 'RenderIf 條件渲染', link: '/zh-HK/components/render-if' },
        { text: 'Breakpoint 斷點偵測', link: '/zh-HK/components/breakpoint' },
        { text: 'MediaQuery 媒體查詢', link: '/zh-HK/components/media-query' },
      ],
    },
  ],
}

// 英文侧边栏
const enSidebar = {
  '/en/guide/': [
    {
      text: 'Getting Started',
      collapsed: false,
      items: [
        { text: 'Introduction',  link: '/en/guide/introduction' },
        { text: 'Quick Start',   link: '/en/guide/getting-started' },
        { text: 'Installation',  link: '/en/guide/installation' },
        { text: 'Changelog',     link: '/en/guide/changelog' },
      ],
    },
    {
      text: 'Design',
      collapsed: false,
      items: [
        { text: 'Design Tokens', link: '/en/guide/tokens' },
        { text: 'Colors',        link: '/en/guide/colors' },
        { text: 'Typography',    link: '/en/guide/typography' },
        { text: 'Spacing',       link: '/en/guide/spacing' },
        { text: 'Theming',       link: '/en/guide/theming' },
      ],
    },
    {
      text: 'Architecture',
      collapsed: false,
      items: [
        { text: 'Overview',       link: '/en/guide/architecture' },
        { text: 'Composables',    link: '/en/guide/composables' },
        { text: 'Directives',     link: '/en/guide/directives' },
        { text: 'Utils',          link: '/en/guide/utils' },
      ],
    },
  ],
  '/en/components/': [
    {
      text: 'Overview',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/en/components/overview' },
      ],
    },
    {
      text: 'Basic (41)',
      collapsed: true,
      items: [
        { text: 'Color', link: '/en/components/color' },
        { text: 'Text', link: '/en/components/text' },
        { text: 'Heading', link: '/en/components/heading' },
        { text: 'Paragraph', link: '/en/components/paragraph' },
        { text: 'Label', link: '/en/components/label' },
        { text: 'Caption', link: '/en/components/caption' },
        { text: 'Code', link: '/en/components/code' },
        { text: 'Quote', link: '/en/components/quote' },
        { text: 'Number', link: '/en/components/number' },
        { text: 'Statistic', link: '/en/components/statistic' },
        { text: 'Counter', link: '/en/components/counter' },
        { text: 'Countdown', link: '/en/components/countdown' },
        { text: 'Currency', link: '/en/components/currency' },
        { text: 'Percentage', link: '/en/components/percentage' },
        { text: 'Icon', link: '/en/components/icon' },
        { text: 'IconButton', link: '/en/components/icon-button' },
        { text: 'Button', link: '/en/components/button' },
        { text: 'ButtonGroup', link: '/en/components/button-group' },
        { text: 'Link', link: '/en/components/link' },
        { text: 'Divider', link: '/en/components/divider' },
        { text: 'Spacer', link: '/en/components/spacer' },
        { text: 'Badge', link: '/en/components/badge' },
        { text: 'Tag', link: '/en/components/tag' },
        { text: 'Chip', link: '/en/components/chip' },
        { text: 'Avatar', link: '/en/components/avatar' },
        { text: 'AvatarGroup', link: '/en/components/avatar-group' },
        { text: 'Image', link: '/en/components/image' },
        { text: 'Picture', link: '/en/components/picture' },
        { text: 'AspectRatio', link: '/en/components/aspect-ratio' },
        { text: 'Skeleton', link: '/en/components/skeleton' },
        { text: 'Spinner', link: '/en/components/spinner' },
        { text: 'Progress', link: '/en/components/progress' },
        { text: 'CircularProgress', link: '/en/components/circular-progress' },
        { text: 'Rating', link: '/en/components/rating' },
        { text: 'Switch', link: '/en/components/switch' },
        { text: 'Slider', link: '/en/components/slider' },
        { text: 'RangeSlider', link: '/en/components/range-slider' },
        { text: 'Clipboard', link: '/en/components/clipboard' },
        { text: 'CopyButton', link: '/en/components/copy-button' },
        { text: 'Highlight', link: '/en/components/highlight' },
        { text: 'VisuallyHidden', link: '/en/components/visually-hidden' },
      ],
    },
    {
      text: 'Layout (32)',
      collapsed: true,
      items: [
        { text: 'Container', link: '/en/components/container' },
        { text: 'Flex', link: '/en/components/flex' },
        { text: 'Grid', link: '/en/components/grid' },
        { text: 'Stack', link: '/en/components/stack' },
        { text: 'HStack', link: '/en/components/h-stack' },
        { text: 'VStack', link: '/en/components/v-stack' },
        { text: 'Center', link: '/en/components/center' },
        { text: 'Space', link: '/en/components/space' },
        { text: 'Wrap', link: '/en/components/wrap' },
        { text: 'DividerLayout', link: '/en/components/divider-layout' },
        { text: 'AspectRatioLayout', link: '/en/components/aspect-ratio-layout' },
        { text: 'Page', link: '/en/components/page' },
        { text: 'PageHeader', link: '/en/components/page-header' },
        { text: 'PageFooter', link: '/en/components/page-footer' },
        { text: 'Section', link: '/en/components/section' },
        { text: 'Sidebar', link: '/en/components/sidebar' },
        { text: 'SidebarLayout', link: '/en/components/sidebar-layout' },
        { text: 'HeaderLayout', link: '/en/components/header-layout' },
        { text: 'FooterLayout', link: '/en/components/footer-layout' },
        { text: 'SplitLayout', link: '/en/components/split-layout' },
        { text: 'DashboardLayout', link: '/en/components/dashboard-layout' },
        { text: 'CardLayout', link: '/en/components/card-layout' },
        { text: 'ListLayout', link: '/en/components/list-layout' },
        { text: 'MediaLayout', link: '/en/components/media-layout' },
        { text: 'ScrollView', link: '/en/components/scroll-view' },
        { text: 'Sticky', link: '/en/components/sticky' },
        { text: 'Portal', link: '/en/components/portal' },
        { text: 'Overlay', link: '/en/components/overlay' },
        { text: 'SafeArea', link: '/en/components/safe-area' },
        { text: 'Viewport', link: '/en/components/viewport' },
        { text: 'FixedLayout', link: '/en/components/fixed-layout' },
        { text: 'FloatingLayout', link: '/en/components/floating-layout' },
      ],
    },
    {
      text: 'Form (53)',
      collapsed: true,
      items: [
        { text: 'Form', link: '/en/components/form' },
        { text: 'FormItem', link: '/en/components/form-item' },
        { text: 'FormLabel', link: '/en/components/form-label' },
        { text: 'FormDescription', link: '/en/components/form-description' },
        { text: 'FormError', link: '/en/components/form-error' },
        { text: 'FormGroup', link: '/en/components/form-group' },
        { text: 'FormField', link: '/en/components/form-field' },
        { text: 'Input', link: '/en/components/input' },
        { text: 'Textarea', link: '/en/components/textarea' },
        { text: 'PasswordInput', link: '/en/components/password-input' },
        { text: 'NumberInput', link: '/en/components/number-input' },
        { text: 'OtpInput', link: '/en/components/otp-input' },
        { text: 'SearchInput', link: '/en/components/search-input' },
        { text: 'UrlInput', link: '/en/components/url-input' },
        { text: 'EmailInput', link: '/en/components/email-input' },
        { text: 'PhoneInput', link: '/en/components/phone-input' },
        { text: 'Select', link: '/en/components/select' },
        { text: 'MultiSelect', link: '/en/components/multi-select' },
        { text: 'TreeSelect', link: '/en/components/tree-select' },
        { text: 'Cascader', link: '/en/components/cascader' },
        { text: 'Checkbox', link: '/en/components/checkbox' },
        { text: 'CheckboxGroup', link: '/en/components/checkbox-group' },
        { text: 'Radio', link: '/en/components/radio' },
        { text: 'RadioGroup', link: '/en/components/radio-group' },
        { text: 'SwitchField', link: '/en/components/switch-field' },
        { text: 'SliderField', link: '/en/components/slider-field' },
        { text: 'RangeSliderField', link: '/en/components/range-slider-field' },
        { text: 'RatingField', link: '/en/components/rating-field' },
        { text: 'DatePicker', link: '/en/components/date-picker' },
        { text: 'TimePicker', link: '/en/components/time-picker' },
        { text: 'DateTimePicker', link: '/en/components/date-time-picker' },
        { text: 'RangePicker', link: '/en/components/range-picker' },
        { text: 'WeekPicker', link: '/en/components/week-picker' },
        { text: 'MonthPicker', link: '/en/components/month-picker' },
        { text: 'YearPicker', link: '/en/components/year-picker' },
        { text: 'ColorPicker', link: '/en/components/color-picker' },
        { text: 'FileUpload', link: '/en/components/file-upload' },
        { text: 'ImageUpload', link: '/en/components/image-upload' },
        { text: 'Dropzone', link: '/en/components/dropzone' },
        { text: 'UploadList', link: '/en/components/upload-list' },
        { text: 'SignaturePad', link: '/en/components/signature-pad' },
        { text: 'RichTextEditor', link: '/en/components/rich-text-editor' },
        { text: 'MarkdownEditor', link: '/en/components/markdown-editor' },
        { text: 'JsonEditor', link: '/en/components/json-editor' },
        { text: 'CodeEditor', link: '/en/components/code-editor' },
        { text: 'TagInput', link: '/en/components/tag-input' },
        { text: 'Autocomplete', link: '/en/components/autocomplete' },
        { text: 'Mention', link: '/en/components/mention' },
        { text: 'Transfer', link: '/en/components/transfer' },
        { text: 'DualList', link: '/en/components/dual-list' },
        { text: 'Stepper', link: '/en/components/stepper' },
        { text: 'WizardForm', link: '/en/components/wizard-form' },
        { text: 'FormArray', link: '/en/components/form-array' },
      ],
    },
    {
      text: 'Data (18)',
      collapsed: true,
      items: [
        { text: 'Table', link: '/en/components/table' },
        { text: 'DataTable', link: '/en/components/data-table' },
        { text: 'VirtualTable', link: '/en/components/virtual-table' },
        { text: 'TreeTable', link: '/en/components/tree-table' },
        { text: 'GridTable', link: '/en/components/grid-table' },
        { text: 'List', link: '/en/components/list' },
        { text: 'VirtualList', link: '/en/components/virtual-list' },
        { text: 'Tree', link: '/en/components/tree' },
        { text: 'DataGrid', link: '/en/components/data-grid' },
        { text: 'StatisticCard', link: '/en/components/statistic-card' },
        { text: 'Metric', link: '/en/components/metric' },
        { text: 'Timeline', link: '/en/components/timeline' },
        { text: 'Calendar', link: '/en/components/calendar' },
        { text: 'Schedule', link: '/en/components/schedule' },
        { text: 'ActivityFeed', link: '/en/components/activity-feed' },
        { text: 'Kanban', link: '/en/components/kanban' },
        { text: 'DataCard', link: '/en/components/data-card' },
        { text: 'Waterfall', link: '/en/components/waterfall' },
      ],
    },
    {
      text: 'Chart (14)',
      collapsed: true,
      items: [
        { text: 'Chart', link: '/en/components/chart' },
        { text: 'LineChart', link: '/en/components/line-chart' },
        { text: 'BarChart', link: '/en/components/bar-chart' },
        { text: 'PieChart', link: '/en/components/pie-chart' },
        { text: 'AreaChart', link: '/en/components/area-chart' },
        { text: 'RadarChart', link: '/en/components/radar-chart' },
        { text: 'ScatterChart', link: '/en/components/scatter-chart' },
        { text: 'Heatmap', link: '/en/components/heatmap' },
        { text: 'Gauge', link: '/en/components/gauge' },
        { text: 'Sparkline', link: '/en/components/sparkline' },
        { text: 'Map', link: '/en/components/map' },
        { text: 'GeoMap', link: '/en/components/geo-map' },
        { text: 'FunnelChart', link: '/en/components/funnel-chart' },
        { text: 'TreemapChart', link: '/en/components/treemap-chart' },
      ],
    },
    {
      text: 'Display (18)',
      collapsed: true,
      items: [
        { text: 'DataViewer', link: '/en/components/data-viewer' },
        { text: 'JsonViewer', link: '/en/components/json-viewer' },
        { text: 'YamlViewer', link: '/en/components/yaml-viewer' },
        { text: 'KeyValue', link: '/en/components/key-value' },
        { text: 'LogViewer', link: '/en/components/log-viewer' },
        { text: 'CodeViewer', link: '/en/components/code-viewer' },
        { text: 'MarkdownViewer', link: '/en/components/markdown-viewer' },
        { text: 'DiffViewer', link: '/en/components/diff-viewer' },
        { text: 'FileTree', link: '/en/components/file-tree' },
        { text: 'FileList', link: '/en/components/file-list' },
        { text: 'FolderTree', link: '/en/components/folder-tree' },
        { text: 'FolderList', link: '/en/components/folder-list' },
        { text: 'MediaGallery', link: '/en/components/media-gallery' },
        { text: 'ProductList', link: '/en/components/product-list' },
        { text: 'UserList', link: '/en/components/user-list' },
        { text: 'NotificationList', link: '/en/components/notification-list' },
        { text: 'Watermark', link: '/en/components/watermark' },
        { text: 'ProfileCard', link: '/en/components/profile-card' },
      ],
    },
    {
      text: 'Feedback (30)',
      collapsed: true,
      items: [
        { text: 'Alert', link: '/en/components/alert' },
        { text: 'Banner', link: '/en/components/banner' },
        { text: 'Callout', link: '/en/components/callout' },
        { text: 'Toast', link: '/en/components/toast' },
        { text: 'Message', link: '/en/components/message' },
        { text: 'Snackbar', link: '/en/components/snackbar' },
        { text: 'Notification', link: '/en/components/notification' },
        { text: 'NotificationCenter', link: '/en/components/notification-center' },
        { text: 'Dialog', link: '/en/components/dialog' },
        { text: 'Modal', link: '/en/components/modal' },
        { text: 'ConfirmDialog', link: '/en/components/confirm-dialog' },
        { text: 'PromptDialog', link: '/en/components/prompt-dialog' },
        { text: 'FullscreenModal', link: '/en/components/fullscreen-modal' },
        { text: 'Drawer', link: '/en/components/drawer' },
        { text: 'BottomSheet', link: '/en/components/bottom-sheet' },
        { text: 'Popover', link: '/en/components/popover' },
        { text: 'Tooltip', link: '/en/components/tooltip' },
        { text: 'HoverCard', link: '/en/components/hover-card' },
        { text: 'ContextMenu', link: '/en/components/context-menu' },
        { text: 'Loading', link: '/en/components/loading' },
        { text: 'LoadingOverlay', link: '/en/components/loading-overlay' },
        { text: 'ProgressBar', link: '/en/components/progress-bar' },
        { text: 'SkeletonLoader', link: '/en/components/skeleton-loader' },
        { text: 'EmptyState', link: '/en/components/empty-state' },
        { text: 'Result', link: '/en/components/result' },
        { text: 'ErrorPage', link: '/en/components/error-page' },
        { text: 'Offline', link: '/en/components/offline' },
        { text: 'Retry', link: '/en/components/retry' },
        { text: 'Tour', link: '/en/components/tour' },
        { text: 'Guide', link: '/en/components/guide' },
      ],
    },
    {
      text: 'Navigation (23)',
      collapsed: true,
      items: [
        { text: 'Menu', link: '/en/components/menu' },
        { text: 'MenuBar', link: '/en/components/menu-bar' },
        { text: 'DropdownMenu', link: '/en/components/dropdown-menu' },
        { text: 'MegaMenu', link: '/en/components/mega-menu' },
        { text: 'Tabs', link: '/en/components/tabs' },
        { text: 'TabBar', link: '/en/components/tab-bar' },
        { text: 'Breadcrumb', link: '/en/components/breadcrumb' },
        { text: 'Pagination', link: '/en/components/pagination' },
        { text: 'Pager', link: '/en/components/pager' },
        { text: 'NavBar', link: '/en/components/nav-bar' },
        { text: 'TopNav', link: '/en/components/top-nav' },
        { text: 'SideNav', link: '/en/components/side-nav' },
        { text: 'BottomNav', link: '/en/components/bottom-nav' },
        { text: 'MobileNav', link: '/en/components/mobile-nav' },
        { text: 'CommandPalette', link: '/en/components/command-palette' },
        { text: 'SearchBar', link: '/en/components/search-bar' },
        { text: 'SearchDialog', link: '/en/components/search-dialog' },
        { text: 'FilterBar', link: '/en/components/filter-bar' },
        { text: 'SortBar', link: '/en/components/sort-bar' },
        { text: 'CategoryNav', link: '/en/components/category-nav' },
        { text: 'TagNav', link: '/en/components/tag-nav' },
        { text: 'AnchorNav', link: '/en/components/anchor-nav' },
        { text: 'FloatingMenu', link: '/en/components/floating-menu' },
      ],
    },
    {
      text: 'Media (27)',
      collapsed: true,
      items: [
        { text: 'ImageViewer', link: '/en/components/image-viewer' },
        { text: 'ImagePreview', link: '/en/components/image-preview' },
        { text: 'ImageZoom', link: '/en/components/image-zoom' },
        { text: 'ImageCropper', link: '/en/components/image-cropper' },
        { text: 'ImageEditor', link: '/en/components/image-editor' },
        { text: 'Gallery', link: '/en/components/gallery' },
        { text: 'Carousel', link: '/en/components/carousel' },
        { text: 'SliderGallery', link: '/en/components/slider-gallery' },
        { text: 'Lightbox', link: '/en/components/lightbox' },
        { text: 'VideoPlayer', link: '/en/components/video-player' },
        { text: 'AudioPlayer', link: '/en/components/audio-player' },
        { text: 'MediaPlayer', link: '/en/components/media-player' },
        { text: 'MediaCard', link: '/en/components/media-card' },
        { text: 'MediaGrid', link: '/en/components/media-grid' },
        { text: 'Camera', link: '/en/components/camera' },
        { text: 'ScreenRecorder', link: '/en/components/screen-recorder' },
        { text: 'AudioRecorder', link: '/en/components/audio-recorder' },
        { text: 'QRScanner', link: '/en/components/qr-scanner' },
        { text: 'BarcodeScanner', link: '/en/components/barcode-scanner' },
        { text: 'AvatarEditor', link: '/en/components/avatar-editor' },
        { text: 'GifPlayer', link: '/en/components/gif-player' },
        { text: 'LottiePlayer', link: '/en/components/lottie-player' },
        { text: 'AnimationPlayer', link: '/en/components/animation-player' },
        { text: 'PosterGenerator', link: '/en/components/poster-generator' },
        { text: 'Thumbnail', link: '/en/components/thumbnail' },
        { text: 'DocumentViewer', link: '/en/components/document-viewer' },
        { text: 'Panorama', link: '/en/components/panorama' },
      ],
    },
    {
      text: 'Advanced (24)',
      collapsed: true,
      items: [
        { text: 'GlobalSearch', link: '/en/components/global-search' },
        { text: 'Spotlight', link: '/en/components/spotlight' },
        { text: 'KanbanBoard', link: '/en/components/kanban-board' },
        { text: 'WorkflowDesigner', link: '/en/components/workflow-designer' },
        { text: 'FlowChart', link: '/en/components/flow-chart' },
        { text: 'MindMap', link: '/en/components/mind-map' },
        { text: 'OrgChart', link: '/en/components/org-chart' },
        { text: 'TreeEditor', link: '/en/components/tree-editor' },
        { text: 'DragList', link: '/en/components/drag-list' },
        { text: 'DragGrid', link: '/en/components/drag-grid' },
        { text: 'DragTree', link: '/en/components/drag-tree' },
        { text: 'SortableList', link: '/en/components/sortable-list' },
        { text: 'SortableTable', link: '/en/components/sortable-table' },
        { text: 'VirtualScroller', link: '/en/components/virtual-scroller' },
        { text: 'InfiniteScroll', link: '/en/components/infinite-scroll' },
        { text: 'SmartTable', link: '/en/components/smart-table' },
        { text: 'QueryBuilder', link: '/en/components/query-builder' },
        { text: 'FilterBuilder', link: '/en/components/filter-builder' },
        { text: 'LayoutBuilder', link: '/en/components/layout-builder' },
        { text: 'DashboardBuilder', link: '/en/components/dashboard-builder' },
        { text: 'PageBuilder', link: '/en/components/page-builder' },
        { text: 'ThemeEditor', link: '/en/components/theme-editor' },
        { text: 'ComponentPlayground', link: '/en/components/component-playground' },
        { text: 'LiveEditor', link: '/en/components/live-editor' },
      ],
    },
    {
      text: 'Utility (20)',
      collapsed: true,
      items: [
        { text: 'FocusTrap', link: '/en/components/focus-trap' },
        { text: 'ClickOutside', link: '/en/components/click-outside' },
        { text: 'ResizeObserver', link: '/en/components/resize-observer' },
        { text: 'IntersectionObserver', link: '/en/components/intersection-observer' },
        { text: 'ScrollLock', link: '/en/components/scroll-lock' },
        { text: 'ScrollSpy', link: '/en/components/scroll-spy' },
        { text: 'Keybinding', link: '/en/components/keybinding' },
        { text: 'Hotkey', link: '/en/components/hotkey' },
        { text: 'ClipboardManager', link: '/en/components/clipboard-manager' },
        { text: 'Fullscreen', link: '/en/components/fullscreen' },
        { text: 'IdleTimer', link: '/en/components/idle-timer' },
        { text: 'VisibilitySensor', link: '/en/components/visibility-sensor' },
        { text: 'DeviceDetector', link: '/en/components/device-detector' },
        { text: 'ThemeProvider', link: '/en/components/theme-provider' },
        { text: 'LocaleProvider', link: '/en/components/locale-provider' },
        { text: 'ConfigProvider', link: '/en/components/config-provider' },
        { text: 'ErrorBoundary', link: '/en/components/error-boundary' },
        { text: 'RenderIf', link: '/en/components/render-if' },
        { text: 'Breakpoint', link: '/en/components/breakpoint' },
        { text: 'MediaQuery', link: '/en/components/media-query' },
      ],
    },
  ],
}

export default defineConfig({
  title: 'Parrot UI',
  description: '基于 uni-app X 的跨终端组件库',

  // 根路径重定向到简体中文
  rewrites: {
    'zh/:rest*': ':rest*',
  },

  // 多语言配置
  locales: {
    root: {
      label: '🇨🇳 简体中文',
      lang: 'zh-CN',
      title: 'Parrot UI',
      description: '基于 uni-app X 的跨终端组件库，支持 Android / iOS / 鸿蒙 / 微信小程序 / Web',
      themeConfig: {
        nav: [
          { text: '指南',           link: '/guide/introduction',   activeMatch: '/guide/' },
          { text: '组件',           link: '/components/overview',    activeMatch: '/components/' },
          { text: '架构',           link: '/guide/architecture' },
          { text: '更新日志',       link: '/guide/changelog' },
        ],
        sidebar: {
          '/guide/': zhSidebar['/zh/guide/'].map(g => ({
            ...g,
            items: g.items.map(i => ({ ...i, link: i.link.replace('/zh/', '/') })),
          })),
          '/components/': zhSidebar['/zh/components/'].map(g => ({
            ...g,
            items: g.items.map(i => ({ ...i, link: i.link.replace('/zh/', '/') })),
          })),
        },
        outline:             { level: [2, 3], label: '本页目录' },
        sidebarMenuLabel:    '目录',
        returnToTopLabel:    '返回顶部',
        darkModeSwitchLabel: '外观',
        lightModeSwitchTitle: '切换至亮色模式',
        darkModeSwitchTitle:  '切换至暗色模式',
        editLink: {
          pattern: 'https://github.com/parrotui/parrotui/edit/main/docs/:path',
          text: '在 GitHub 上编辑此页',
        },
        lastUpdated: { text: '最后更新' },
        docFooter: { prev: '上一页', next: '下一页' },
      },
    },

    'zh-HK': {
      label: '🇭🇰 繁體中文',
      lang: 'zh-HK',
      title: 'Parrot UI',
      description: '基於 uni-app X 的跨終端元件庫',
      themeConfig: {
        nav: [
          { text: '指南',           link: '/zh-HK/guide/introduction',   activeMatch: '/zh-HK/guide/' },
          { text: '元件',           link: '/zh-HK/components/overview',    activeMatch: '/zh-HK/components/' },
          { text: '架構',           link: '/zh-HK/guide/architecture' },
          { text: '更新日誌',       link: '/zh-HK/guide/changelog' },
        ],
        sidebar: zhTWSidebar,
        outline:             { level: [2, 3], label: '本頁目錄' },
        sidebarMenuLabel:    '目錄',
        returnToTopLabel:    '返回頂部',
        darkModeSwitchLabel: '外觀',
        lightModeSwitchTitle: '切換至亮色模式',
        darkModeSwitchTitle:  '切換至暗色模式',
        editLink: {
          pattern: 'https://github.com/parrotui/parrotui/edit/main/docs/:path',
          text: '在 GitHub 上編輯此頁',
        },
        lastUpdated: { text: '最後更新' },
        docFooter: { prev: '上一頁', next: '下一頁' },
      },
    },

    en: {
      label: '🇺🇸 English',
      lang: 'en-US',
      title: 'Parrot UI',
      description: 'Cross-platform component library based on uni-app X',
      themeConfig: {
        nav: [
          { text: 'Guide',          link: '/en/guide/introduction',  activeMatch: '/en/guide/' },
          { text: 'Components',     link: '/en/components/overview',   activeMatch: '/en/components/' },
          { text: 'Architecture',   link: '/en/guide/architecture' },
          { text: 'Changelog',      link: '/en/guide/changelog' },
        ],
        sidebar: enSidebar,
        outline:             { level: [2, 3], label: 'On this page' },
        sidebarMenuLabel:    'Menu',
        returnToTopLabel:    'Return to top',
        darkModeSwitchLabel: 'Appearance',
        lightModeSwitchTitle: 'Switch to light mode',
        darkModeSwitchTitle:  'Switch to dark mode',
        editLink: {
          pattern: 'https://github.com/parrotui/parrotui/edit/main/docs/:path',
          text: 'Edit this page on GitHub',
        },
        lastUpdated: { text: 'Last updated' },
        docFooter: { prev: 'Previous page', next: 'Next page' },
      },
    },
  },

  // 基础路径
  base: '/',

  // 共享主题配置
  themeConfig: {
    logo: '/icon.svg',
    siteTitle: 'Parrot UI',

    // 社交链接
    socialLinks: [
      { icon: 'github', link: 'https://github.com/parrotui/parrotui' },
      { icon: { svg: weiboSvg }, link: 'https://weibo.com/parrotui', target: '_blank' },
    ],

    // 页脚
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026-present Parrot UI Contributors',
    },

    // 搜索
    search: { provider: 'local' },
  },

  // Markdown 配置
  markdown: {
    lineNumbers: true,
  },

  // Head 注入
  head: [
    ['link', { rel: 'icon',             href: '/favicon.ico' }],
    ['link', { rel: 'icon',             href: '/favicon-32x32.png', type: 'image/png', sizes: '32x32' }],
    ['link', { rel: 'icon',             href: '/favicon-16x16.png', type: 'image/png', sizes: '16x16' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' }],
    ['link', { rel: 'manifest',         href: '/site.webmanifest' }],
    ['meta', { name: 'theme-color',     content: '#1a7eff' }],
    ['meta', { property: 'og:type',        content: 'website' }],
    ['meta', { property: 'og:title',       content: 'Parrot UI' }],
    ['meta', { property: 'og:description', content: '基于 uni-app X 的跨终端组件库' }],
    ['meta', { property: 'og:url',         content: 'https://doc.parrotui.com' }],
    ['meta', { property: 'og:image',       content: 'https://doc.parrotui.com/android-chrome-512x512.png' }],
  ],
})
